-- =============================================================================
-- test_legacy_fixture.sql   (TEST HARNESS ONLY — never run against production)
--
-- Recreates the ORIGINAL schema the Flutter app was written against, so the
-- migrations can be tested against a database that is not empty. This is the
-- situation that produced:
--
--   ERROR: 42703: column "owneruserid" does not exist
--
-- Reconstructed from lib/services/supabase_service.dart and AGENTS.md.
-- =============================================================================

create schema if not exists auth;

do $$
begin
  if not exists (select 1 from pg_class where relname = 'users'
                   and relnamespace = 'auth'::regnamespace) then
    create table auth.users (
      id         uuid primary key,
      email      text unique,
      created_at timestamptz not null default now()
    );
    execute $fn$
      create function auth.uid() returns uuid
      language sql stable as $body$
        select nullif(current_setting('ws.test_uid', true), '')::uuid
      $body$;
    $fn$;
  end if;
end
$$;

create table public.ws_tblorganization (
  orgid       bigint generated by default as identity primary key,
  authuserid  uuid,
  orgname     text not null,
  ownername   text default '',
  phone       text default '',
  address     text default '',
  isactive    boolean default true,
  createddate timestamptz default now()
);

create table public.ws_tblinternalusers (
  internaluserid bigint generated by default as identity primary key,
  orgid          bigint references public.ws_tblorganization(orgid),
  authuserid     uuid,
  fullname       text not null,
  -- The original app constrained this to two values. The new schema has six
  -- roles, so provision_organization() inserting 'owner' trips it. Reproduces:
  --   new row for relation "ws_tblinternalusers" violates check constraint
  --   "ws_tblinternalusers_role_check"
  role           text default 'staff'
                 constraint ws_tblinternalusers_role_check
                 check (role in ('admin','staff')),
  phone          text,
  isactive       boolean default true
);

create table public.ws_tblareas (
  areaid        bigint generated by default as identity primary key,
  orgid         bigint references public.ws_tblorganization(orgid),
  areaname      text not null,
  rateperbottle numeric(12,2) default 0,
  deliverydays  text,
  isactive      boolean default true
);

create table public.ws_tblcustomers (
  customerid    bigint generated by default as identity primary key,
  orgid         bigint references public.ws_tblorganization(orgid),
  authuserid    uuid,
  areaid        bigint references public.ws_tblareas(areaid),
  customername  text not null,
  address       text,
  phone         text,
  rateoverride  numeric(12,2),
  depositamount numeric(12,2) default 0,
  bottlebalance int default 0,
  isactive      boolean default true,
  createddate   timestamptz default now()
);

create table public.ws_tbldeliveries (
  deliveryid       bigint generated by default as identity primary key,
  orgid            bigint references public.ws_tblorganization(orgid),
  customerid       bigint references public.ws_tblcustomers(customerid),
  deliveredbyid    bigint references public.ws_tblinternalusers(internaluserid),
  deliverydate     date not null default current_date,
  bottlesdelivered int default 0,
  bottlesreturned  int default 0,
  bottlebalance    int default 0,
  rateapplied      numeric(12,2) default 0,
  amountcharged    numeric(14,2) default 0,
  notes            text
);

create table public.ws_tblpayments (
  paymentid      bigint generated by default as identity primary key,
  orgid          bigint references public.ws_tblorganization(orgid),
  customerid     bigint references public.ws_tblcustomers(customerid),
  deliveryid     bigint references public.ws_tbldeliveries(deliveryid),
  receivedbyid   bigint references public.ws_tblinternalusers(internaluserid),
  paymentdate    date not null default current_date,
  amountreceived numeric(14,2) not null,
  paymentmethod  text default 'cash'
                 constraint ws_tblpayments_paymentmethod_check
                 check (paymentmethod in ('cash','easypaisa','jazzcash','bank','other')),
  referenceno    text,
  notes          text
);

create table public.ws_tblbottleinventory (
  inventoryid          bigint generated by default as identity primary key,
  orgid                bigint references public.ws_tblorganization(orgid),
  snapshotdate         date not null default current_date,
  totalbottles         int default 0,
  bottleswithcustomers int default 0,
  bottlesinstock       int default 0,
  bottleslost          int default 0,
  notes                text
);

create view public.vw_ws_customerbalance as
select c.*, a.areaname, a.rateperbottle, 0::numeric as outstandingdue
from public.ws_tblcustomers c
left join public.ws_tblareas a on a.areaid = c.areaid;

-- A little live data, so the migration is exercised against a table that is not
-- empty. Adding a NOT NULL column to a populated table is where naive upgrade
-- scripts fail.
insert into auth.users (id, email) values (gen_random_uuid(), 'legacy@kentwater.pk');

insert into public.ws_tblorganization (authuserid, orgname, ownername, phone, address)
select id, 'Legacy Water Co', 'Legacy Owner', '0300-0000000', 'Lahore'
from auth.users where email = 'legacy@kentwater.pk';

insert into public.ws_tblinternalusers (orgid, authuserid, fullname, role)
select 1, id, 'Legacy Owner', 'admin' from auth.users where email = 'legacy@kentwater.pk';

insert into public.ws_tblareas (orgid, areaname, rateperbottle) values (1, 'Legacy Area', 200);

insert into public.ws_tblcustomers (orgid, areaid, customername, phone, bottlebalance)
values (1, 1, 'Legacy Customer', '0300-1111111', 3);

insert into public.ws_tbldeliveries
  (orgid, customerid, deliverydate, bottlesdelivered, bottlesreturned, bottlebalance, rateapplied, amountcharged)
values (1, 1, current_date - 5, 2, 1, 4, 200, 400);

insert into public.ws_tblpayments (orgid, customerid, paymentdate, amountreceived)
values (1, 1, current_date - 5, 400);
