-- =============================================================================
-- 002_tenancy_and_rbac.sql
-- Organizations, membership, roles, permissions, subscriptions.
--
-- DESIGN NOTE — WHY A DEDICATED MEMBERSHIP TABLE
-- The current Flutter code resolves "which orgs can I see" by querying
-- ws_tblinternalusers UNION ws_tblcustomers. If RLS policies on those two
-- tables also had to consult those same two tables, Postgres would recurse and
-- error with "infinite recursion detected in policy".
--
-- ws_tblmemberships breaks that cycle. It is the ONE table RLS consults, it is
-- read through a SECURITY DEFINER function, and its own policy is a plain
-- `authuserid = current_uid()` self-check that touches no other table.
-- Staff records (ws_tblinternalusers) and portal links (ws_tblcustomers) hang
-- off it and are kept in sync by triggers.
--
-- DESIGN NOTE — ws_tblorganization.authuserid
-- The existing column implies exactly one owner per organization, which
-- contradicts the requirement that a user can own multiple organizations and
-- that an organization has multiple users. It is retained as `owneruserid` for
-- backwards compatibility and for "who to bill", but it is NOT used for access
-- control. Authorization reads ws_tblmemberships only.
-- =============================================================================

-- ─── Organizations ───────────────────────────────────────────────────────────

create table if not exists public.ws_tblorganization (
  orgid             bigint generated by default as identity primary key,
  publicid          uuid        not null default gen_random_uuid() unique,
  orgname           text        not null,
  businessname      text,
  owneruserid       uuid        references auth.users(id) on delete set null,
  ownername         text        not null default '',
  email             text,
  phone             text        not null default '',
  address           text        not null default '',
  logourl           text,
  currency          text        not null default 'PKR',
  currencysymbol    text        not null default 'Rs',
  dateformat        text        not null default 'dd-MM-yyyy',
  timezone          text        not null default 'Asia/Karachi',
  invoiceprefix     text        not null default 'INV-',
  receiptprefix     text        not null default 'RCPT-',
  deliveryprefix    text        not null default 'DEL-',
  -- Report layout is per-organization and data-driven, not compiled in.
  cardsettings      jsonb       not null default '{
    "pagesize": "A5",
    "showdeposit": true,
    "showsignature": true,
    "columns": ["date","delivered","received","balance","amount","paid"]
  }'::jsonb,
  isactive          boolean     not null default true,
  createddate       timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

-- Legacy alias: existing Dart reads/writes `authuserid` on this table.
-- A generated column cannot be written to, so this is a plain column kept in
-- step with owneruserid by trigger. Remove once the client is updated.
alter table public.ws_tblorganization
  add column if not exists authuserid uuid;

create or replace function ws.tg_org_sync_owner()
returns trigger
language plpgsql
set search_path = ws, public, pg_catalog
as $$
begin
  if new.owneruserid is null and new.authuserid is not null then
    new.owneruserid := new.authuserid;
  end if;
  new.authuserid := new.owneruserid;
  new.updated_at := now();
  return new;
end
$$;

drop trigger if exists trg_org_sync_owner on public.ws_tblorganization;
create trigger trg_org_sync_owner
  before insert or update on public.ws_tblorganization
  for each row execute function ws.tg_org_sync_owner();

create index if not exists ix_org_owner on public.ws_tblorganization(owneruserid);

-- ─── Permissions catalogue (global, not tenant-scoped) ───────────────────────

create table if not exists public.ws_tblpermissions (
  permcode    text primary key,
  module      text not null,
  label       text not null,
  sortorder   int  not null default 0
);

insert into public.ws_tblpermissions (permcode, module, label, sortorder) values
  ('org.view',        'Organization', 'View organization settings', 10),
  ('org.manage',      'Organization', 'Change organization settings', 11),
  ('users.view',      'Users',        'View users',                  20),
  ('users.manage',    'Users',        'Invite and edit users',       21),
  ('customers.view',  'Customers',    'View customers',              30),
  ('customers.manage','Customers',    'Create and edit customers',   31),
  ('vendors.view',    'Vendors',      'View vendors',                40),
  ('vendors.manage',  'Vendors',      'Create and edit vendors',     41),
  ('products.view',   'Products',     'View products and pricing',   50),
  ('products.manage', 'Products',     'Edit products and pricing',   51),
  ('delivery.view',   'Deliveries',   'View deliveries',             60),
  ('delivery.manage', 'Deliveries',   'Record deliveries',           61),
  ('payments.view',   'Payments',     'View payments',               70),
  ('payments.manage', 'Payments',     'Record payments',             71),
  ('purchases.view',  'Purchases',    'View purchases',              80),
  ('purchases.manage','Purchases',    'Record purchases',            81),
  ('accounting.view', 'Accounting',   'View ledgers and journals',   90),
  ('accounting.manage','Accounting',  'Post manual journal entries', 91),
  ('reports.view',    'Reports',      'Run reports',                100),
  ('reports.all',     'Reports',      'Run all reports',            101)
on conflict (permcode) do nothing;

-- ─── Roles (per organization, so tenants can define their own) ───────────────

create table if not exists public.ws_tblroles (
  roleid      bigint generated by default as identity primary key,
  orgid       bigint not null references public.ws_tblorganization(orgid) on delete cascade,
  rolecode    text   not null,
  rolename    text   not null,
  issystem    boolean not null default false,   -- system roles cannot be deleted
  isportal    boolean not null default false,   -- true = customer portal role
  createddate timestamptz not null default now(),
  unique (orgid, rolecode)
);

create table if not exists public.ws_tblrolepermissions (
  roleid   bigint not null references public.ws_tblroles(roleid) on delete cascade,
  permcode text   not null references public.ws_tblpermissions(permcode) on delete cascade,
  primary key (roleid, permcode)
);

-- ─── Membership: the single source of truth for access control ───────────────

create table if not exists public.ws_tblmemberships (
  membershipid bigint generated by default as identity primary key,
  orgid        bigint not null references public.ws_tblorganization(orgid) on delete cascade,
  authuserid   uuid   not null references auth.users(id) on delete cascade,
  roleid       bigint not null references public.ws_tblroles(roleid) on delete restrict,
  -- Set when this membership is a customer-portal login rather than staff.
  -- Populated by trigger from ws_tblcustomers; scopes portal row visibility.
  customerid   bigint,
  isactive     boolean not null default true,
  createddate  timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  unique (orgid, authuserid)
);

create index if not exists ix_membership_user on public.ws_tblmemberships(authuserid) where isactive;
create index if not exists ix_membership_org  on public.ws_tblmemberships(orgid)      where isactive;

drop trigger if exists trg_membership_touch on public.ws_tblmemberships;
create trigger trg_membership_touch
  before update on public.ws_tblmemberships
  for each row execute function ws.tg_touch_updated_at();

-- ─── Non-recursive tenant resolution (the core of RLS) ───────────────────────

-- SECURITY DEFINER: reads ws_tblmemberships with RLS bypassed. This is safe
-- because the WHERE clause is pinned to the caller's own uid; a caller cannot
-- influence which rows come back.
create or replace function ws.member_org_ids()
returns setof bigint
language sql
stable
security definer
set search_path = ws, public, pg_catalog
as $$
  select m.orgid
  from public.ws_tblmemberships m
  where m.authuserid = ws.current_uid()
    and m.isactive
$$;

create or replace function ws.is_member(p_orgid bigint)
returns boolean
language sql
stable
security definer
set search_path = ws, public, pg_catalog
as $$
  select exists (
    select 1 from public.ws_tblmemberships m
    where m.authuserid = ws.current_uid()
      and m.orgid = p_orgid
      and m.isactive
  )
$$;

-- Returns the customerid this user is scoped to in the given org, or NULL for
-- staff. Portal RLS policies use this: staff see all customers, a portal user
-- sees only rows where customerid = ws.portal_customer_id(orgid).
create or replace function ws.portal_customer_id(p_orgid bigint)
returns bigint
language sql
stable
security definer
set search_path = ws, public, pg_catalog
as $$
  select m.customerid
  from public.ws_tblmemberships m
  where m.authuserid = ws.current_uid()
    and m.orgid = p_orgid
    and m.isactive
  limit 1
$$;

-- Permission check. Replaces the hardcoded admin/staff/customer enum in
-- lib/models/ws_models.dart: permissions are data, not a Dart switch.
create or replace function ws.has_perm(p_orgid bigint, p_perm text)
returns boolean
language sql
stable
security definer
set search_path = ws, public, pg_catalog
as $$
  select exists (
    select 1
    from public.ws_tblmemberships m
    join public.ws_tblrolepermissions rp on rp.roleid = m.roleid
    where m.authuserid = ws.current_uid()
      and m.orgid = p_orgid
      and m.isactive
      and rp.permcode = p_perm
  )
$$;

-- ─── Internal (staff) users — profile data only, not authorization ──────────

create table if not exists public.ws_tblinternalusers (
  internaluserid bigint generated by default as identity primary key,
  orgid          bigint not null references public.ws_tblorganization(orgid) on delete cascade,
  authuserid     uuid   references auth.users(id) on delete set null,
  membershipid   bigint references public.ws_tblmemberships(membershipid) on delete set null,
  fullname       text   not null,
  phone          text,
  -- Denormalised role code for display and for the legacy Dart read path.
  -- Authorization must use ws.has_perm(), never this column.
  role           text   not null default 'staff',
  isactive       boolean not null default true,
  createddate    timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  unique (orgid, authuserid)
);

create index if not exists ix_internalusers_org on public.ws_tblinternalusers(orgid);

drop trigger if exists trg_internalusers_touch on public.ws_tblinternalusers;
create trigger trg_internalusers_touch
  before update on public.ws_tblinternalusers
  for each row execute function ws.tg_touch_updated_at();

-- ─── Subscriptions and plan limits ──────────────────────────────────────────

create table if not exists public.ws_tblplans (
  plancode        text primary key,
  planname        text not null,
  monthlyprice    numeric(12,2) not null default 0,
  maxcustomers    int,      -- null = unlimited
  maxusers        int,
  allowaccounting boolean not null default false,
  allowroutes     boolean not null default false,
  allowapi        boolean not null default false,
  sortorder       int not null default 0
);

insert into public.ws_tblplans
  (plancode, planname, monthlyprice, maxcustomers, maxusers, allowaccounting, allowroutes, allowapi, sortorder)
values
  ('free',       'Free',          0,    50,   1, false, false, false, 1),
  ('basic',      'Basic',      1500,   500,   5, true,  true,  false, 2),
  ('pro',        'Professional',4000,  null, null, true,  true,  true,  3),
  ('enterprise', 'Enterprise',    0,   null, null, true,  true,  true,  4)
on conflict (plancode) do nothing;

create table if not exists public.ws_tblsubscriptions (
  subscriptionid bigint generated by default as identity primary key,
  orgid          bigint not null references public.ws_tblorganization(orgid) on delete cascade,
  plancode       text   not null references public.ws_tblplans(plancode),
  status         text   not null default 'trialing'
                 check (status in ('trialing','active','past_due','canceled','expired')),
  trialstartdate date,
  trialenddate   date,
  periodstart    date,
  periodend      date,
  createddate    timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create unique index if not exists ux_subscription_active_per_org
  on public.ws_tblsubscriptions(orgid)
  where status in ('trialing','active','past_due');

create table if not exists public.ws_tblsubscriptionpayments (
  subpaymentid   bigint generated by default as identity primary key,
  subscriptionid bigint not null references public.ws_tblsubscriptions(subscriptionid) on delete cascade,
  orgid          bigint not null references public.ws_tblorganization(orgid) on delete cascade,
  amount         numeric(12,2) not null check (amount >= 0),
  paiddate       date not null default current_date,
  gatewayref     text,
  createddate    timestamptz not null default now()
);

-- ─── Provisioning: create an org with sane defaults in one transaction ───────
-- Called from the client with the new org's details. Replaces the current
-- multi-step client-side sequence in AuthService.registerOrganization(), which
-- can leave an organization with no membership row if the second insert fails.

-- ws.ensure_org_roles(orgid)
-- Creates the seven default roles and their permission sets for an
-- organization that does not have them yet. Idempotent.
--
-- Extracted from provision_organization() so that organizations which already
-- existed before this schema was installed can be given roles too. Without it
-- there is no way to bootstrap a pre-existing tenant: every RLS policy resolves
-- through a membership, a membership needs a role, and roles were only ever
-- created as a side effect of creating a brand new organization.
create or replace function ws.ensure_org_roles(p_orgid bigint)
returns void
language plpgsql
security definer
set search_path = ws, public, pg_catalog
as $ensure$
declare
  v_orgid bigint := p_orgid;
begin
  insert into public.ws_tblroles (orgid, rolecode, rolename, issystem, isportal) values
    (v_orgid, 'owner',      'Owner',      true,  false),
    (v_orgid, 'admin',      'Admin',      true,  false),
    (v_orgid, 'accountant', 'Accountant', true,  false),
    (v_orgid, 'sales',      'Sales',      true,  false),
    (v_orgid, 'delivery',   'Delivery',   true,  false),
    (v_orgid, 'readonly',   'Read Only',  true,  false),
    (v_orgid, 'customer',   'Customer',   true,  true)
  on conflict (orgid, rolecode) do nothing;

  -- Owner gets every permission that exists, so adding a new permission later
  -- does not silently lock the owner out of their own organization.

  -- owner: everything
  insert into public.ws_tblrolepermissions (roleid, permcode)
  select r.roleid, p.permcode
  from public.ws_tblroles r cross join public.ws_tblpermissions p
  where r.orgid = v_orgid and r.rolecode = 'owner'
  on conflict (roleid, permcode) do nothing;

  -- admin: everything except billing-level org changes are still allowed here;
  -- differentiate later if you add an org.billing permission.
  insert into public.ws_tblrolepermissions (roleid, permcode)
  select r.roleid, p.permcode
  from public.ws_tblroles r cross join public.ws_tblpermissions p
  where r.orgid = v_orgid and r.rolecode = 'admin'
  on conflict (roleid, permcode) do nothing;

  insert into public.ws_tblrolepermissions (roleid, permcode)
  select r.roleid, x.permcode
  from public.ws_tblroles r
  cross join (values
    ('customers.view'),('customers.manage'),
    ('vendors.view'),('vendors.manage'),
    ('products.view'),
    ('delivery.view'),
    ('payments.view'),('payments.manage'),
    ('purchases.view'),('purchases.manage'),
    ('accounting.view'),('accounting.manage'),
    ('reports.view'),('reports.all')
  ) as x(permcode)
  where r.orgid = v_orgid and r.rolecode = 'accountant'
  on conflict (roleid, permcode) do nothing;

  insert into public.ws_tblrolepermissions (roleid, permcode)
  select r.roleid, x.permcode
  from public.ws_tblroles r
  cross join (values
    ('customers.view'),('customers.manage'),
    ('products.view'),
    ('delivery.view'),('delivery.manage'),
    ('payments.view'),('payments.manage'),
    ('reports.view')
  ) as x(permcode)
  where r.orgid = v_orgid and r.rolecode = 'sales'
  on conflict (roleid, permcode) do nothing;

  insert into public.ws_tblrolepermissions (roleid, permcode)
  select r.roleid, x.permcode
  from public.ws_tblroles r
  cross join (values
    ('customers.view'),
    ('products.view'),
    ('delivery.view'),('delivery.manage'),
    ('reports.view')
  ) as x(permcode)
  where r.orgid = v_orgid and r.rolecode = 'delivery'
  on conflict (roleid, permcode) do nothing;

  insert into public.ws_tblrolepermissions (roleid, permcode)
  select r.roleid, x.permcode
  from public.ws_tblroles r
  cross join (values
    ('customers.view'),('vendors.view'),('products.view'),
    ('delivery.view'),('payments.view'),('purchases.view'),
    ('accounting.view'),('reports.view')
  ) as x(permcode)
  where r.orgid = v_orgid and r.rolecode = 'readonly'
  on conflict (roleid, permcode) do nothing;

  -- portal role: read-only on its own rows. Row scoping is done by RLS via
  -- ws.portal_customer_id(), not by these permission codes.
  insert into public.ws_tblrolepermissions (roleid, permcode)
  select r.roleid, x.permcode
  from public.ws_tblroles r
  cross join (values ('delivery.view'),('payments.view')) as x(permcode)
  where r.orgid = v_orgid and r.rolecode = 'customer'
  on conflict (roleid, permcode) do nothing;
end
$ensure$;

-- ws.provision_organization() takes the owner uid explicitly so that seeds,
-- imports and admin tooling can create an organization on someone's behalf.
-- It lives in the private `ws` schema and is NOT reachable over PostgREST.
-- The public wrapper below is the only client-callable entry point and always
-- passes the caller's own uid.
create or replace function ws.provision_organization(
  p_uid       uuid,
  p_orgname   text,
  p_ownername text default '',
  p_phone     text default '',
  p_address   text default '',
  p_currency  text default 'PKR'
)
returns bigint
language plpgsql
security definer
set search_path = ws, public, pg_catalog
as $$
declare
  v_uid    uuid := p_uid;
  v_orgid  bigint;
  v_roleid bigint;
begin
  if v_uid is null then
    raise exception 'provision_organization: no owner uid supplied'
      using errcode = '42501';
  end if;

  insert into public.ws_tblorganization
    (orgname, businessname, owneruserid, ownername, phone, address, currency)
  values
    (p_orgname, p_orgname, v_uid, p_ownername, p_phone, p_address, p_currency)
  returning orgid into v_orgid;

  perform ws.ensure_org_roles(v_orgid);

  select roleid into v_roleid
  from public.ws_tblroles
  where orgid = v_orgid and rolecode = 'owner';

  insert into public.ws_tblmemberships (orgid, authuserid, roleid)
  values (v_orgid, v_uid, v_roleid);

  insert into public.ws_tblinternalusers (orgid, authuserid, fullname, role, phone, membershipid)
  select v_orgid, v_uid, coalesce(nullif(p_ownername,''), 'Owner'), 'owner', p_phone, m.membershipid
  from public.ws_tblmemberships m
  where m.orgid = v_orgid and m.authuserid = v_uid;

  insert into public.ws_tblsubscriptions
    (orgid, plancode, status, trialstartdate, trialenddate, periodstart, periodend)
  values
    (v_orgid, 'free', 'trialing', current_date, current_date + 14,
     current_date, current_date + 14);

  return v_orgid;
end
$$;

create or replace function public.ws_create_organization(
  p_orgname   text,
  p_ownername text default '',
  p_phone     text default '',
  p_address   text default '',
  p_currency  text default 'PKR'
)
returns bigint
language plpgsql
security definer
set search_path = ws, public, pg_catalog
as $$
declare v_uid uuid := ws.current_uid();
begin
  if v_uid is null then
    raise exception 'ws_create_organization: not authenticated' using errcode = '42501';
  end if;
  return ws.provision_organization(v_uid, p_orgname, p_ownername, p_phone, p_address, p_currency);
end
$$;

revoke all on function ws.provision_organization(uuid,text,text,text,text,text) from public;
revoke all on function public.ws_create_organization(text,text,text,text,text) from public;
grant execute on function public.ws_create_organization(text,text,text,text,text) to authenticated;
