-- =============================================================================
-- 003_master_data.sql
-- Areas, routes, bottle types, products, dynamic pricing, customers, vendors.
--
-- DESIGN NOTE — WHY BOTTLE TYPE IS SEPARATE FROM PRODUCT
-- A product is what you sell and invoice ("19 Litre Mineral Water", Rs 250).
-- A bottle type is the returnable physical asset that moves with it. They are
-- not the same cardinality: two products (Water 19L, Water 19L Premium) can
-- circulate on the same 19L bottle, and a 500ml case is a product with no
-- returnable at all. Collapsing them is the change that forces a migration
-- later, so they are split now.
--
-- DESIGN NOTE — PRICE RESOLUTION
-- Precedence is customer > customer group > area > product default, each with an
-- effective date window. ws.resolve_price() is the single implementation; the
-- delivery trigger and any quoting UI must both call it so they cannot disagree.
-- =============================================================================

-- ─── Areas ───────────────────────────────────────────────────────────────────

create table if not exists public.ws_tblareas (
  areaid        bigint generated by default as identity primary key,
  orgid         bigint not null references public.ws_tblorganization(orgid) on delete cascade,
  areaname      text   not null,
  -- Retained for backwards compatibility with the current Flutter code, which
  -- reads area.rateperbottle. New code should rely on ws_tblproductprices;
  -- migration 003 seeds an area-scoped price row from this value.
  rateperbottle numeric(12,2) not null default 0 check (rateperbottle >= 0),
  deliverydays  text,
  isactive      boolean not null default true,
  createddate   timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (orgid, areaname)
);

-- ─── Routes, vehicles, drivers ───────────────────────────────────────────────

create table if not exists public.ws_tblroutes (
  routeid     bigint generated by default as identity primary key,
  orgid       bigint not null references public.ws_tblorganization(orgid) on delete cascade,
  routecode   text   not null,
  routename   text   not null,
  areaid      bigint references public.ws_tblareas(areaid) on delete set null,
  driverid    bigint references public.ws_tblinternalusers(internaluserid) on delete set null,
  vehicleno   text,
  isactive    boolean not null default true,
  createddate timestamptz not null default now(),
  unique (orgid, routecode)
);

-- ─── Bottle types (returnable assets) ────────────────────────────────────────

create table if not exists public.ws_tblbottletypes (
  bottletypeid   bigint generated by default as identity primary key,
  orgid          bigint not null references public.ws_tblorganization(orgid) on delete cascade,
  bottlecode     text   not null,
  bottlename     text   not null,
  capacitylitres numeric(8,2),
  depositamount  numeric(12,2) not null default 0 check (depositamount >= 0),
  isdefault      boolean not null default false,
  isactive       boolean not null default true,
  createddate    timestamptz not null default now(),
  unique (orgid, bottlecode)
);

-- Exactly one default bottle type per org. The paper delivery card has a single
-- balance column, so the PDF renders the default type unless asked otherwise.
create unique index if not exists ux_bottletype_default_per_org
  on public.ws_tblbottletypes(orgid) where isdefault;

-- ─── Products ────────────────────────────────────────────────────────────────

create table if not exists public.ws_tblproducts (
  productid      bigint generated by default as identity primary key,
  orgid          bigint not null references public.ws_tblorganization(orgid) on delete cascade,
  productcode    text   not null,
  productname    text   not null,
  producttype    text   not null default 'water'
                 check (producttype in ('water','bottle','cap','filter','packaging','service','other')),
  unitlabel      text   not null default 'Bottle',
  sizelabel      text,
  capacitylitres numeric(8,2),
  -- Returnable link. NOT NULL only when the product moves a bottle.
  bottletypeid   bigint references public.ws_tblbottletypes(bottletypeid) on delete restrict,
  bottlesperunit int    not null default 1 check (bottlesperunit >= 0),
  saleprice      numeric(12,2) not null default 0 check (saleprice >= 0),
  purchaseprice  numeric(12,2) not null default 0 check (purchaseprice >= 0),
  trackinventory boolean not null default true,
  isactive       boolean not null default true,
  createddate    timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  unique (orgid, productcode),
  -- A product that claims to move bottles must say which type.
  constraint ck_product_bottle_consistency check (
    (bottletypeid is null and bottlesperunit = 0)
    or (bottletypeid is not null and bottlesperunit >= 1)
  )
);

-- ─── Customer groups (a pricing tier, e.g. Hotel / Office / Home) ────────────

create table if not exists public.ws_tblcustomergroups (
  groupid     bigint generated by default as identity primary key,
  orgid       bigint not null references public.ws_tblorganization(orgid) on delete cascade,
  groupname   text   not null,
  isactive    boolean not null default true,
  createddate timestamptz not null default now(),
  unique (orgid, groupname)
);

-- ─── Customers ───────────────────────────────────────────────────────────────

create table if not exists public.ws_tblcustomers (
  customerid           bigint generated by default as identity primary key,
  orgid                bigint not null references public.ws_tblorganization(orgid) on delete cascade,
  customercode         text,
  customername         text   not null,
  contactperson        text,
  phone                text,
  email                text,
  address              text,
  areaid               bigint references public.ws_tblareas(areaid) on delete set null,
  routeid              bigint references public.ws_tblroutes(routeid) on delete set null,
  groupid              bigint references public.ws_tblcustomergroups(groupid) on delete set null,
  -- Portal login. NULL = this customer has no app access.
  authuserid           uuid   references auth.users(id) on delete set null,
  creditlimit          numeric(12,2),
  depositamount        numeric(12,2) not null default 0 check (depositamount >= 0),
  openingbalance       numeric(12,2) not null default 0,
  -- Legacy single-number bottle balance. Kept so the current Flutter build does
  -- not break, but it is now a DERIVED cache maintained by the bottle trigger
  -- for the DEFAULT bottle type only. Authoritative per-type balances live in
  -- ws_tblcustomerbottlebalances. Do not write to this column.
  bottlebalance        int    not null default 0,
  -- Legacy flat rate override for the default product. Superseded by
  -- ws_tblproductprices; still honoured by ws.resolve_price() as a fallback.
  rateoverride         numeric(12,2),
  isactive             boolean not null default true,
  createddate          timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  unique (orgid, customercode),
  unique (orgid, authuserid)
);

create index if not exists ix_customers_org_active on public.ws_tblcustomers(orgid) where isactive;
create index if not exists ix_customers_area on public.ws_tblcustomers(areaid);
create index if not exists ix_customers_authuser on public.ws_tblcustomers(authuserid) where authuserid is not null;

create table if not exists public.ws_tblcustomeraddresses (
  addressid    bigint generated by default as identity primary key,
  orgid        bigint not null references public.ws_tblorganization(orgid) on delete cascade,
  customerid   bigint not null references public.ws_tblcustomers(customerid) on delete cascade,
  label        text,
  address      text not null,
  isprimary    boolean not null default false,
  createddate  timestamptz not null default now()
);

-- Keep the membership row in step with the customer's portal link, so RLS
-- scoping cannot drift from the customer record.
create or replace function ws.tg_customer_sync_membership()
returns trigger
language plpgsql
security definer
set search_path = ws, public, pg_catalog
as $$
declare
  v_roleid bigint;
begin
  if new.authuserid is not null then
    select roleid into v_roleid
    from public.ws_tblroles
    where orgid = new.orgid and rolecode = 'customer';

    if v_roleid is not null then
      insert into public.ws_tblmemberships (orgid, authuserid, roleid, customerid)
      values (new.orgid, new.authuserid, v_roleid, new.customerid)
      on conflict (orgid, authuserid)
      do update set customerid = excluded.customerid, isactive = true;
    end if;
  end if;

  -- Portal access revoked: deactivate the membership rather than delete it, so
  -- history and audit trails survive.
  if tg_op = 'UPDATE'
     and old.authuserid is not null
     and (new.authuserid is null or new.authuserid <> old.authuserid) then
    update public.ws_tblmemberships
      set isactive = false
    where orgid = old.orgid
      and authuserid = old.authuserid
      and customerid = old.customerid;
  end if;

  return null;
end
$$;

drop trigger if exists trg_customer_sync_membership on public.ws_tblcustomers;
create trigger trg_customer_sync_membership
  after insert or update of authuserid on public.ws_tblcustomers
  for each row execute function ws.tg_customer_sync_membership();

-- ─── Vendors ─────────────────────────────────────────────────────────────────

create table if not exists public.ws_tblvendors (
  vendorid       bigint generated by default as identity primary key,
  orgid          bigint not null references public.ws_tblorganization(orgid) on delete cascade,
  vendorcode     text,
  vendorname     text   not null,
  contactperson  text,
  phone          text,
  email          text,
  address        text,
  openingbalance numeric(12,2) not null default 0,
  isactive       boolean not null default true,
  createddate    timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  unique (orgid, vendorcode)
);

create index if not exists ix_vendors_org_active on public.ws_tblvendors(orgid) where isactive;

-- ─── Payment methods (per-org, so tenants can add their own wallets) ─────────

create table if not exists public.ws_tblpaymentmethods (
  methodid    bigint generated by default as identity primary key,
  orgid       bigint not null references public.ws_tblorganization(orgid) on delete cascade,
  methodcode  text   not null,
  methodname  text   not null,
  -- Which cash/bank account this method settles into. Set in migration 004.
  accountid   bigint,
  isactive    boolean not null default true,
  sortorder   int not null default 0,
  unique (orgid, methodcode)
);

-- ─── Dynamic pricing ─────────────────────────────────────────────────────────

create table if not exists public.ws_tblproductprices (
  priceid       bigint generated by default as identity primary key,
  orgid         bigint not null references public.ws_tblorganization(orgid) on delete cascade,
  productid     bigint not null references public.ws_tblproducts(productid) on delete cascade,
  -- Scope: exactly one of customerid / groupid / areaid may be set.
  -- All three NULL = the organization-wide default for this product.
  customerid    bigint references public.ws_tblcustomers(customerid) on delete cascade,
  groupid       bigint references public.ws_tblcustomergroups(groupid) on delete cascade,
  areaid        bigint references public.ws_tblareas(areaid) on delete cascade,
  price         numeric(12,2) not null check (price >= 0),
  effectivefrom date not null default current_date,
  effectiveto   date,
  createddate   timestamptz not null default now(),
  constraint ck_price_single_scope check (
    (customerid is not null)::int + (groupid is not null)::int + (areaid is not null)::int <= 1
  ),
  constraint ck_price_date_order check (effectiveto is null or effectiveto >= effectivefrom)
);

create index if not exists ix_price_lookup
  on public.ws_tblproductprices(orgid, productid, effectivefrom desc);
create index if not exists ix_price_customer on public.ws_tblproductprices(customerid) where customerid is not null;

-- Overlapping windows for the same scope make pricing non-deterministic.
-- These partial unique indexes forbid two open-ended rows per scope; date-range
-- overlap beyond that is caught by the validation trigger below.
create or replace function ws.tg_price_no_overlap()
returns trigger
language plpgsql
set search_path = ws, public, pg_catalog
as $$
begin
  if exists (
    select 1 from public.ws_tblproductprices p
    where p.orgid = new.orgid
      and p.productid = new.productid
      and p.priceid <> coalesce(new.priceid, -1)
      and p.customerid is not distinct from new.customerid
      and p.groupid    is not distinct from new.groupid
      and p.areaid     is not distinct from new.areaid
      and daterange(p.effectivefrom, p.effectiveto, '[]')
          && daterange(new.effectivefrom, new.effectiveto, '[]')
  ) then
    raise exception
      'overlapping price window for product % in this scope (from % to %)',
      new.productid, new.effectivefrom, coalesce(new.effectiveto::text, 'open')
      using errcode = '23505';
  end if;
  return new;
end
$$;

drop trigger if exists trg_price_no_overlap on public.ws_tblproductprices;
create trigger trg_price_no_overlap
  before insert or update on public.ws_tblproductprices
  for each row execute function ws.tg_price_no_overlap();

-- -----------------------------------------------------------------------------
-- ws.resolve_price(orgid, productid, customerid, date)
-- The single source of truth for "what does this customer pay today".
-- Precedence: customer > customer group > area > org default > legacy area
-- rateperbottle / customer rateoverride > product.saleprice.
-- -----------------------------------------------------------------------------
create or replace function ws.resolve_price(
  p_orgid      bigint,
  p_productid  bigint,
  p_customerid bigint,
  p_on         date default current_date
)
returns numeric
language plpgsql
stable
set search_path = ws, public, pg_catalog
as $$
declare
  v_areaid           bigint;
  v_groupid          bigint;
  v_price            numeric(12,2);
  v_legacy           numeric(12,2);
  v_isdefaultbottle  boolean;
begin
  select c.areaid, c.groupid, c.rateoverride
    into v_areaid, v_groupid, v_legacy
  from public.ws_tblcustomers c
  where c.customerid = p_customerid and c.orgid = p_orgid;

  select p.price into v_price
  from public.ws_tblproductprices p
  where p.orgid = p_orgid
    and p.productid = p_productid
    and p_on between p.effectivefrom and coalesce(p.effectiveto, 'infinity'::date)
    and (
         p.customerid = p_customerid
      or (p.customerid is null and p.groupid = v_groupid)
      or (p.customerid is null and p.groupid is null and p.areaid = v_areaid)
      or (p.customerid is null and p.groupid is null and p.areaid is null)
    )
  order by
    (p.customerid is not null) desc,
    (p.groupid    is not null) desc,
    (p.areaid     is not null) desc,
    p.effectivefrom desc
  limit 1;

  if v_price is not null then
    return v_price;
  end if;

  -- Legacy fallbacks (customer.rateoverride, area.rateperbottle) exist so an org
  -- that has not migrated its pricing still bills correctly. They describe a
  -- per-BOTTLE rate, so they must apply ONLY to the default returnable product.
  -- Applying them to everything would bill a case of 500ml at the 19L water
  -- rate — which is precisely what the first test run caught.
  select (p.bottletypeid is not null and b.isdefault) into v_isdefaultbottle
  from public.ws_tblproducts p
  left join public.ws_tblbottletypes b on b.bottletypeid = p.bottletypeid
  where p.productid = p_productid;

  if coalesce(v_isdefaultbottle, false) then
    if v_legacy is not null then
      return v_legacy;
    end if;

    select a.rateperbottle into v_price
    from public.ws_tblareas a where a.areaid = v_areaid and a.rateperbottle > 0;
    if v_price is not null then
      return v_price;
    end if;
  end if;

  select pr.saleprice into v_price
  from public.ws_tblproducts pr where pr.productid = p_productid;

  return coalesce(v_price, 0);
end
$$;

-- Exposed read-only wrapper so the UI can preview a price without duplicating
-- the precedence logic in Dart.
create or replace function public.ws_resolve_price(
  p_orgid bigint, p_productid bigint, p_customerid bigint, p_on date default current_date
)
returns numeric
language sql
stable
security definer
set search_path = ws, public, pg_catalog
as $$
  select case
    when ws.is_member(p_orgid) then ws.resolve_price(p_orgid, p_productid, p_customerid, p_on)
    else null
  end
$$;

revoke all on function public.ws_resolve_price(bigint,bigint,bigint,date) from public;
grant execute on function public.ws_resolve_price(bigint,bigint,bigint,date) to authenticated;

-- ─── updated_at triggers ─────────────────────────────────────────────────────
do $$
declare t text;
begin
  foreach t in array array[
    'ws_tblareas','ws_tblproducts','ws_tblcustomers','ws_tblvendors'
  ] loop
    execute format('drop trigger if exists trg_touch_%1$s on public.%1$s', t);
    execute format(
      'create trigger trg_touch_%1$s before update on public.%1$s
       for each row execute function ws.tg_touch_updated_at()', t);
  end loop;
end
$$;
