-- =============================================================================
-- 004_accounting_core.sql
-- Chart of accounts, journal entries, and in-transaction posting.
--
-- YOU CHOSE "BOTH, JOURNAL DERIVED". READ THIS BEFORE GOING FURTHER.
--
-- The risk you accepted is drift: the subsidiary tables say the customer owes
-- 5,500 and the AR control account says 5,200, and nobody notices for months.
-- A background poster (cron job, queue worker, edge function) makes that risk
-- permanent, because any crash between "insert sale" and "post journal" leaves
-- the two out of step and there is no bound on how long it stays that way.
--
-- So this schema does NOT use a background poster. Journal entries are written
-- by AFTER triggers in the same database transaction as the source row. Either
-- both exist or neither does — the failure mode is eliminated structurally
-- rather than monitored.
--
-- Two consequences you should know about:
--   1. A posting-rule bug now aborts the delivery insert instead of silently
--      producing a wrong report. That is deliberate. Loud beats wrong.
--   2. Backdating still needs care: vw_ws_trialbalance is period-filtered, so a
--      sale posted late lands in the period of its document date, not today.
--
-- vw_ws_reconciliation (migration 007) compares the AR/AP control accounts
-- against the subsidiary sums. It should always return zero rows. Put it on the
-- dashboard; a non-empty result means a posting rule is wrong.
-- =============================================================================

-- ─── Chart of accounts ───────────────────────────────────────────────────────

create table if not exists public.ws_tblaccounts (
  accountid    bigint generated by default as identity primary key,
  orgid        bigint not null references public.ws_tblorganization(orgid) on delete cascade,
  accountcode  text   not null,
  accountname  text   not null,
  accounttype  text   not null
               check (accounttype in ('asset','liability','equity','income','expense')),
  parentid     bigint references public.ws_tblaccounts(accountid) on delete set null,
  -- Control accounts are posted to by triggers only and are reconciled against
  -- their subsidiary ledger. Manual journal entries against them are rejected.
  controlfor   text
               check (controlfor in ('ar','ap','cash','bank','inventory','bottledeposit')),
  isactive     boolean not null default true,
  createddate  timestamptz not null default now(),
  unique (orgid, accountcode)
);

create unique index if not exists ux_account_control_per_org
  on public.ws_tblaccounts(orgid, controlfor)
  where controlfor is not null and controlfor not in ('cash','bank');

create index if not exists ix_accounts_org on public.ws_tblaccounts(orgid);

-- Normal balance side: +1 means debits increase the account.
create or replace function ws.account_sign(p_type text)
returns int
language sql
immutable
set search_path = pg_catalog
as $$
  select case when p_type in ('asset','expense') then 1 else -1 end
$$;

-- ─── Journal ─────────────────────────────────────────────────────────────────

create table if not exists public.ws_tbljournalentries (
  journalid    bigint generated by default as identity primary key,
  orgid        bigint not null references public.ws_tblorganization(orgid) on delete cascade,
  entrydate    date   not null default current_date,
  entryno      text,
  -- What produced this entry. 'manual' is the only value a human may insert.
  sourcetype   text   not null
               check (sourcetype in ('manual','sale','customerpayment','purchase','vendorpayment','bottleadjustment','opening')),
  sourceid     bigint,
  memo         text,
  isposted     boolean not null default true,
  createdby    uuid   references auth.users(id) on delete set null,
  createddate  timestamptz not null default now(),
  unique (orgid, sourcetype, sourceid)
);

create index if not exists ix_journal_org_date on public.ws_tbljournalentries(orgid, entrydate);

create table if not exists public.ws_tbljournalentrydetails (
  detailid   bigint generated by default as identity primary key,
  journalid   bigint not null references public.ws_tbljournalentries(journalid) on delete cascade,
  orgid       bigint not null references public.ws_tblorganization(orgid) on delete cascade,
  accountid   bigint not null references public.ws_tblaccounts(accountid) on delete restrict,
  -- Subsidiary keys: let the journal be sliced per customer/vendor without a
  -- separate ledger table. This is what makes reconciliation cheap.
  customerid  bigint references public.ws_tblcustomers(customerid) on delete set null,
  vendorid    bigint references public.ws_tblvendors(vendorid) on delete set null,
  debit       numeric(14,2) not null default 0 check (debit  >= 0),
  credit      numeric(14,2) not null default 0 check (credit >= 0),
  description text,
  constraint ck_detail_one_side check (
    (debit > 0 and credit = 0) or (credit > 0 and debit = 0) or (debit = 0 and credit = 0)
  )
);

create index if not exists ix_jdetail_journal  on public.ws_tbljournalentrydetails(journalid);
create index if not exists ix_jdetail_account  on public.ws_tbljournalentrydetails(orgid, accountid);
create index if not exists ix_jdetail_customer on public.ws_tbljournalentrydetails(orgid, customerid) where customerid is not null;
create index if not exists ix_jdetail_vendor   on public.ws_tbljournalentrydetails(orgid, vendorid)   where vendorid is not null;

-- Cross-tenant guard: a detail line must belong to the same org as its header
-- and its account.
create or replace function ws.tg_jdetail_validate()
returns trigger
language plpgsql
set search_path = ws, public, pg_catalog
as $$
declare
  v_header_org bigint;
  v_acct_org   bigint;
begin
  select orgid into v_header_org from public.ws_tbljournalentries where journalid = new.journalid;
  select orgid into v_acct_org   from public.ws_tblaccounts       where accountid = new.accountid;

  perform ws.assert_same_org(new.orgid, v_header_org, 'journal detail vs entry');
  perform ws.assert_same_org(new.orgid, v_acct_org,   'journal detail vs account');
  return new;
end
$$;

drop trigger if exists trg_jdetail_validate on public.ws_tbljournalentrydetails;
create trigger trg_jdetail_validate
  before insert or update on public.ws_tbljournalentrydetails
  for each row execute function ws.tg_jdetail_validate();

-- -----------------------------------------------------------------------------
-- Balanced-entry enforcement.
-- A DEFERRABLE constraint trigger runs at COMMIT, so an entry can be built up
-- line by line and still be checked. Without DEFERRABLE the first line would
-- always fail, which is why naive implementations end up with no check at all.
-- -----------------------------------------------------------------------------
create or replace function ws.tg_journal_must_balance()
returns trigger
language plpgsql
set search_path = ws, public, pg_catalog
as $$
declare
  v_journalid bigint := coalesce(new.journalid, old.journalid);
  v_diff      numeric(14,2);
  v_lines     int;
begin
  select coalesce(sum(debit),0) - coalesce(sum(credit),0), count(*)
    into v_diff, v_lines
  from public.ws_tbljournalentrydetails
  where journalid = v_journalid;

  -- Header deleted (cascade): nothing to check.
  if not exists (select 1 from public.ws_tbljournalentries where journalid = v_journalid) then
    return null;
  end if;

  if v_lines = 0 then
    raise exception 'journal entry % has no lines', v_journalid using errcode = '23514';
  end if;

  if v_diff <> 0 then
    raise exception 'journal entry % is unbalanced by %', v_journalid, v_diff
      using errcode = '23514';
  end if;

  return null;
end
$$;

drop trigger if exists trg_journal_must_balance on public.ws_tbljournalentrydetails;
create constraint trigger trg_journal_must_balance
  after insert or update or delete on public.ws_tbljournalentrydetails
  deferrable initially deferred
  for each row execute function ws.tg_journal_must_balance();

-- Manual entries may not touch AR/AP control accounts: those are owned by the
-- subsidiary ledgers, and a hand-posted line there is exactly how drift starts.
create or replace function ws.tg_journal_guard_control()
returns trigger
language plpgsql
set search_path = ws, public, pg_catalog
as $$
declare
  v_source text;
  v_control text;
begin
  select sourcetype into v_source from public.ws_tbljournalentries where journalid = new.journalid;
  select controlfor into v_control from public.ws_tblaccounts    where accountid = new.accountid;

  if v_source = 'manual' and v_control in ('ar','ap') then
    raise exception
      'account % is the % control account; post a sale/payment document instead of a manual journal',
      new.accountid, v_control
      using errcode = '42501';
  end if;
  return new;
end
$$;

drop trigger if exists trg_journal_guard_control on public.ws_tbljournalentrydetails;
create trigger trg_journal_guard_control
  before insert on public.ws_tbljournalentrydetails
  for each row execute function ws.tg_journal_guard_control();

-- ─── Posting helpers used by the operations triggers ─────────────────────────

create or replace function ws.account_by_code(p_orgid bigint, p_code text)
returns bigint
language plpgsql
stable
set search_path = ws, public, pg_catalog
as $$
declare v_id bigint;
begin
  select accountid into v_id
  from public.ws_tblaccounts
  where orgid = p_orgid and accountcode = p_code and isactive;

  if v_id is null then
    raise exception
      'chart of accounts is missing account % for org % — run ws_seed_chart_of_accounts()',
      p_code, p_orgid
      using errcode = '23503';
  end if;
  return v_id;
end
$$;

create or replace function ws.account_by_control(p_orgid bigint, p_control text)
returns bigint
language plpgsql
stable
set search_path = ws, public, pg_catalog
as $$
declare v_id bigint;
begin
  select accountid into v_id
  from public.ws_tblaccounts
  where orgid = p_orgid and controlfor = p_control and isactive
  order by accountid
  limit 1;

  if v_id is null then
    raise exception 'no % control account configured for org %', p_control, p_orgid
      using errcode = '23503';
  end if;
  return v_id;
end
$$;

-- Creates (or replaces) the journal entry for a source document. Idempotent on
-- (orgid, sourcetype, sourceid): re-posting an edited document rewrites its
-- lines rather than duplicating them.
create or replace function ws.journal_upsert_header(
  p_orgid      bigint,
  p_sourcetype text,
  p_sourceid   bigint,
  p_date       date,
  p_memo       text
)
returns bigint
language plpgsql
set search_path = ws, public, pg_catalog
as $$
declare v_journalid bigint;
begin
  insert into public.ws_tbljournalentries (orgid, sourcetype, sourceid, entrydate, memo, createdby)
  values (p_orgid, p_sourcetype, p_sourceid, p_date, p_memo, ws.current_uid())
  on conflict (orgid, sourcetype, sourceid)
  do update set entrydate = excluded.entrydate, memo = excluded.memo
  returning journalid into v_journalid;

  delete from public.ws_tbljournalentrydetails where journalid = v_journalid;
  return v_journalid;
end
$$;

create or replace function ws.journal_line(
  p_journalid  bigint,
  p_orgid      bigint,
  p_accountid  bigint,
  p_debit      numeric,
  p_credit     numeric,
  p_customerid bigint default null,
  p_vendorid   bigint default null,
  p_desc       text   default null
)
returns void
language plpgsql
set search_path = ws, public, pg_catalog
as $$
begin
  if coalesce(p_debit,0) = 0 and coalesce(p_credit,0) = 0 then
    return;   -- skip zero lines rather than clutter the ledger
  end if;
  insert into public.ws_tbljournalentrydetails
    (journalid, orgid, accountid, customerid, vendorid, debit, credit, description)
  values
    (p_journalid, p_orgid, p_accountid, p_customerid, p_vendorid,
     coalesce(p_debit,0), coalesce(p_credit,0), p_desc);
end
$$;

-- ─── Default chart of accounts ───────────────────────────────────────────────

create or replace function ws.seed_chart_of_accounts(p_orgid bigint)
returns void
language plpgsql
security definer
set search_path = ws, public, pg_catalog
as $$
begin
  insert into public.ws_tblaccounts (orgid, accountcode, accountname, accounttype, controlfor) values
    (p_orgid, '1000', 'Cash in Hand',              'asset',     'cash'),
    (p_orgid, '1010', 'Bank Account',              'asset',     'bank'),
    (p_orgid, '1100', 'Accounts Receivable',       'asset',     'ar'),
    (p_orgid, '1200', 'Inventory',                 'asset',     'inventory'),
    (p_orgid, '1300', 'Bottles in Circulation',    'asset',     null),
    (p_orgid, '2000', 'Accounts Payable',          'liability', 'ap'),
    (p_orgid, '2100', 'Bottle Deposits Held',      'liability', 'bottledeposit'),
    (p_orgid, '3000', 'Owner Equity',              'equity',    null),
    (p_orgid, '3900', 'Opening Balance Equity',    'equity',    null),
    (p_orgid, '4000', 'Water Sales',               'income',    null),
    (p_orgid, '4100', 'Other Income',              'income',    null),
    (p_orgid, '5000', 'Cost of Goods Sold',        'expense',   null),
    (p_orgid, '5100', 'Bottle Loss and Damage',    'expense',   null),
    (p_orgid, '5200', 'Delivery and Fuel',         'expense',   null),
    (p_orgid, '5900', 'Other Expenses',            'expense',   null)
  on conflict (orgid, accountcode) do nothing;

  -- Point the default payment methods at their settlement accounts.
  insert into public.ws_tblpaymentmethods (orgid, methodcode, methodname, accountid, sortorder)
  select p_orgid, x.code, x.name, ws.account_by_code(p_orgid, x.acct), x.ord
  from (values
    ('cash',      'Cash',          '1000', 1),
    ('easypaisa', 'Easypaisa',     '1010', 2),
    ('jazzcash',  'JazzCash',      '1010', 3),
    ('bank',      'Bank Transfer', '1010', 4),
    ('other',     'Other',         '1000', 5)
  ) as x(code, name, acct, ord)
  on conflict (orgid, methodcode) do nothing;
end
$$;

create or replace function public.ws_seed_chart_of_accounts(p_orgid bigint)
returns void
language plpgsql
security definer
set search_path = ws, public, pg_catalog
as $$
begin
  if not ws.is_member(p_orgid) then
    raise exception 'not a member of org %', p_orgid using errcode = '42501';
  end if;
  perform ws.seed_chart_of_accounts(p_orgid);
end
$$;

revoke all on function ws.seed_chart_of_accounts(bigint) from public;
revoke all on function public.ws_seed_chart_of_accounts(bigint) from public;
grant execute on function public.ws_seed_chart_of_accounts(bigint) to authenticated;

-- `add constraint` has no IF NOT EXISTS in Postgres, so a bare ALTER makes this
-- whole file fail on a second run with "constraint already exists" — and these
-- files WILL be re-run while a migration is being sorted out.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'fk_paymentmethod_account'
      and conrelid = 'public.ws_tblpaymentmethods'::regclass
  ) then
    alter table public.ws_tblpaymentmethods
      add constraint fk_paymentmethod_account
      foreign key (accountid) references public.ws_tblaccounts(accountid)
      on delete set null;
  end if;
end
$$;
