-- =============================================================================
-- 005_operations_and_triggers.sql
-- Deliveries, bottle movements, customer payments, document numbering.
--
-- DESIGN NOTE — WHY THE HEADER KEEPS AGGREGATE COLUMNS
-- ws_tbldeliveries has both normalised line items (ws_tbldeliverydetails) and
-- cached totals (bottlesdelivered, bottlesreturned, amountcharged). The cache is
-- not laziness: the paper card, the daily route sheet and the customer ledger
-- all read one row per delivery, and the existing Flutter code already reads
-- these columns. They are maintained by trigger and are never client-writable.
--
-- DESIGN NOTE — BOTTLE BALANCE IS DERIVED, NOT STORED
-- ws_tblbottletransactions is append-only and is the only truth. Two caches are
-- maintained from it by trigger:
--   ws_tblcustomerbottlebalances  (per customer per bottle type — authoritative cache)
--   ws_tblcustomers.bottlebalance (default bottle type only — legacy, for the
--                                  current Flutter build; do not write to it)
-- Recompute either from history at any time with ws_rebuild_bottle_balances().
-- =============================================================================

-- ─── Document number sequences ───────────────────────────────────────────────

create table if not exists public.ws_tbldocumentsequences (
  orgid     bigint not null references public.ws_tblorganization(orgid) on delete cascade,
  doctype   text   not null check (doctype in ('delivery','invoice','receipt','purchase','vendorpayment','journal')),
  prefix    text   not null default '',
  nextno    bigint not null default 1,
  padwidth  int    not null default 6,
  primary key (orgid, doctype)
);

-- UPDATE ... RETURNING takes a row lock, so concurrent delivery inserts cannot
-- receive the same number. A plain sequence would be gapless-unsafe per tenant.
create or replace function ws.next_docnumber(p_orgid bigint, p_doctype text)
returns text
language plpgsql
set search_path = ws, public, pg_catalog
as $$
declare
  v_prefix text;
  v_no     bigint;
  v_pad    int;
begin
  insert into public.ws_tbldocumentsequences (orgid, doctype, prefix)
  values (p_orgid, p_doctype, '')
  on conflict (orgid, doctype) do nothing;

  update public.ws_tbldocumentsequences
     set nextno = nextno + 1
   where orgid = p_orgid and doctype = p_doctype
  returning prefix, nextno - 1, padwidth into v_prefix, v_no, v_pad;

  if v_prefix = '' then
    select case p_doctype
             when 'delivery' then deliveryprefix
             when 'invoice'  then invoiceprefix
             when 'receipt'  then receiptprefix
             else upper(left(p_doctype, 3)) || '-'
           end
      into v_prefix
    from public.ws_tblorganization where orgid = p_orgid;
  end if;

  return coalesce(v_prefix,'') || lpad(v_no::text, v_pad, '0');
end
$$;

-- ─── Bottle balance cache ────────────────────────────────────────────────────

create table if not exists public.ws_tblcustomerbottlebalances (
  orgid        bigint not null references public.ws_tblorganization(orgid) on delete cascade,
  customerid   bigint not null references public.ws_tblcustomers(customerid) on delete cascade,
  bottletypeid bigint not null references public.ws_tblbottletypes(bottletypeid) on delete cascade,
  balance      int    not null default 0,
  updated_at   timestamptz not null default now(),
  primary key (customerid, bottletypeid)
);

create index if not exists ix_bottlebal_org on public.ws_tblcustomerbottlebalances(orgid);

-- ─── Bottle inventory snapshots (LEGACY) ─────────────────────────────────────
-- Superseded by vw_ws_bottleposition, which derives the same figures from the
-- bottle ledger instead of relying on someone remembering to take a snapshot.
-- Created here because the original app's Dart still reads it
-- (WsDataService.fetchLatestSnapshot / insertSnapshot), and without a definition
-- a FRESH install would 404 on that call while an upgraded install would not —
-- the worst kind of environment-dependent bug.
--
-- Migration 008 enables RLS on every ws_tbl% table. A table with RLS enabled and
-- no policy returns zero rows to everyone, so it needs explicit policies there
-- too; see the master-data policy loop.
create table if not exists public.ws_tblbottleinventory (
  inventoryid          bigint generated by default as identity primary key,
  orgid                bigint not null references public.ws_tblorganization(orgid) on delete cascade,
  snapshotdate         date   not null default current_date,
  totalbottles         int    not null default 0,
  bottleswithcustomers int    not null default 0,
  bottlesinstock       int    not null default 0,
  bottleslost          int    not null default 0,
  notes                text,
  createddate          timestamptz not null default now()
);

create index if not exists ix_bottleinventory_org
  on public.ws_tblbottleinventory(orgid, snapshotdate desc);

-- ─── Deliveries ──────────────────────────────────────────────────────────────

create table if not exists public.ws_tbldeliveries (
  deliveryid       bigint generated by default as identity primary key,
  orgid            bigint not null references public.ws_tblorganization(orgid) on delete cascade,
  customerid       bigint not null references public.ws_tblcustomers(customerid) on delete restrict,
  routeid          bigint references public.ws_tblroutes(routeid) on delete set null,
  deliveredbyid    bigint references public.ws_tblinternalusers(internaluserid) on delete set null,
  deliverydate     date   not null default current_date,
  referenceno      text,
  notes            text,

  -- Trigger-maintained caches. Client writes are ignored (see tg_delivery_seal).
  bottlesdelivered int           not null default 0,
  bottlesreturned  int           not null default 0,
  bottlebalance    int           not null default 0,   -- default bottle type, after this delivery
  rateapplied      numeric(12,2) not null default 0,   -- default product's resolved rate
  amountcharged    numeric(14,2) not null default 0,

  isvoid           boolean not null default false,
  createdby        uuid   references auth.users(id) on delete set null,
  createddate      timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  unique (orgid, referenceno)
);

create index if not exists ix_deliveries_org_date  on public.ws_tbldeliveries(orgid, deliverydate desc);
create index if not exists ix_deliveries_customer  on public.ws_tbldeliveries(orgid, customerid, deliverydate);
create index if not exists ix_deliveries_route     on public.ws_tbldeliveries(routeid, deliverydate);

create table if not exists public.ws_tbldeliverydetails (
  deliverydetailid bigint generated by default as identity primary key,
  deliveryid       bigint not null references public.ws_tbldeliveries(deliveryid) on delete cascade,
  orgid            bigint not null references public.ws_tblorganization(orgid) on delete cascade,
  productid        bigint not null references public.ws_tblproducts(productid) on delete restrict,
  deliveredqty     numeric(12,2) not null default 0 check (deliveredqty >= 0),
  returnedqty      numeric(12,2) not null default 0 check (returnedqty  >= 0),
  unitprice        numeric(12,2) not null default 0 check (unitprice    >= 0),
  amount           numeric(14,2) not null default 0,
  notes            text
);

create index if not exists ix_deliverydetails_delivery on public.ws_tbldeliverydetails(deliveryid);

-- ─── Bottle transactions (append-only history) ───────────────────────────────

create table if not exists public.ws_tblbottletransactions (
  bottletxnid   bigint generated by default as identity primary key,
  orgid         bigint not null references public.ws_tblorganization(orgid) on delete cascade,
  customerid    bigint references public.ws_tblcustomers(customerid) on delete restrict,
  bottletypeid  bigint not null references public.ws_tblbottletypes(bottletypeid) on delete restrict,
  deliveryid    bigint references public.ws_tbldeliveries(deliveryid) on delete cascade,
  txndate       date   not null default current_date,
  txntype       text   not null
                check (txntype in ('opening','delivery','return','damaged','lost','adjustment')),
  -- Signed movement from the ORGANIZATION's point of view of what the customer
  -- holds: positive = customer now holds more bottles.
  qty           int    not null,
  balancebefore int    not null,
  balanceafter  int    not null,
  notes         text,
  createdby     uuid   references auth.users(id) on delete set null,
  createddate   timestamptz not null default now(),
  constraint ck_bottletxn_math check (balanceafter = balancebefore + qty)
);

create index if not exists ix_bottletxn_customer
  on public.ws_tblbottletransactions(orgid, customerid, bottletypeid, txndate, bottletxnid);
create index if not exists ix_bottletxn_delivery on public.ws_tblbottletransactions(deliveryid);

-- Append-only. Corrections are made with a compensating 'adjustment' row so the
-- audit trail survives; this is the whole point of a transaction-based design.
create or replace function ws.tg_bottletxn_append_only()
returns trigger
language plpgsql
set search_path = ws, public, pg_catalog
as $$
begin
  raise exception
    'ws_tblbottletransactions is append-only; insert a compensating adjustment row instead of %',
    lower(tg_op)
    using errcode = '42501';
end
$$;

drop trigger if exists trg_bottletxn_append_only on public.ws_tblbottletransactions;
create trigger trg_bottletxn_append_only
  before update or delete on public.ws_tblbottletransactions
  for each row execute function ws.tg_bottletxn_append_only();

-- Fill balancebefore/balanceafter and hold a per-(customer, bottle type) lock so
-- two concurrent deliveries to the same customer cannot interleave and compute
-- the same "before" value.
create or replace function ws.tg_bottletxn_compute_balance()
returns trigger
language plpgsql
set search_path = ws, public, pg_catalog
as $$
declare
  v_before int;
  v_org    bigint;
begin
  if new.customerid is null then
    -- Stock-side movement (e.g. bottles bought from a vendor): no customer balance.
    new.balancebefore := 0;
    new.balanceafter  := new.qty;
    return new;
  end if;

  select orgid into v_org from public.ws_tblcustomers where customerid = new.customerid;
  perform ws.assert_same_org(new.orgid, v_org, 'bottle transaction vs customer');

  select orgid into v_org from public.ws_tblbottletypes where bottletypeid = new.bottletypeid;
  perform ws.assert_same_org(new.orgid, v_org, 'bottle transaction vs bottle type');

  perform pg_advisory_xact_lock(
    hashtextextended(new.customerid::text || ':' || new.bottletypeid::text, 0)
  );

  select coalesce(balance, 0) into v_before
  from public.ws_tblcustomerbottlebalances
  where customerid = new.customerid and bottletypeid = new.bottletypeid;

  new.balancebefore := coalesce(v_before, 0);
  new.balanceafter  := new.balancebefore + new.qty;
  return new;
end
$$;

drop trigger if exists trg_bottletxn_compute on public.ws_tblbottletransactions;
create trigger trg_bottletxn_compute
  before insert on public.ws_tblbottletransactions
  for each row execute function ws.tg_bottletxn_compute_balance();

-- Maintain the two caches.
create or replace function ws.tg_bottletxn_apply_cache()
returns trigger
language plpgsql
set search_path = ws, public, pg_catalog
as $$
declare
  v_isdefault boolean;
begin
  if new.customerid is null then
    return null;
  end if;

  insert into public.ws_tblcustomerbottlebalances (orgid, customerid, bottletypeid, balance)
  values (new.orgid, new.customerid, new.bottletypeid, new.balanceafter)
  on conflict (customerid, bottletypeid)
  do update set balance = new.balanceafter, updated_at = now();

  select isdefault into v_isdefault
  from public.ws_tblbottletypes where bottletypeid = new.bottletypeid;

  if coalesce(v_isdefault, false) then
    update public.ws_tblcustomers
       set bottlebalance = new.balanceafter
     where customerid = new.customerid;
  end if;

  return null;
end
$$;

drop trigger if exists trg_bottletxn_cache on public.ws_tblbottletransactions;
create trigger trg_bottletxn_cache
  after insert on public.ws_tblbottletransactions
  for each row execute function ws.tg_bottletxn_apply_cache();

-- ─── Customer payments ───────────────────────────────────────────────────────
-- Balance-forward, not invoice-allocated. The paper card works this way: money
-- reduces the running balance, it is not matched to a specific delivery. Adding
-- allocation later means a ws_tblpaymentallocations child table; nothing here
-- has to change. Do not add it before a customer actually asks for per-invoice
-- aging, because it doubles the reconciliation surface.

create table if not exists public.ws_tblpayments (
  paymentid      bigint generated by default as identity primary key,
  orgid          bigint not null references public.ws_tblorganization(orgid) on delete cascade,
  customerid     bigint not null references public.ws_tblcustomers(customerid) on delete restrict,
  deliveryid     bigint references public.ws_tbldeliveries(deliveryid) on delete set null,
  receivedbyid   bigint references public.ws_tblinternalusers(internaluserid) on delete set null,
  methodid       bigint references public.ws_tblpaymentmethods(methodid) on delete set null,
  paymentdate    date   not null default current_date,
  amountreceived numeric(14,2) not null check (amountreceived > 0),
  -- Legacy text column the current Flutter code writes (paymentmethod.name).
  paymentmethod  text   not null default 'cash',
  receiptno      text,
  referenceno    text,
  notes          text,
  isvoid         boolean not null default false,
  createdby      uuid   references auth.users(id) on delete set null,
  createddate    timestamptz not null default now(),
  unique (orgid, receiptno)
);

create index if not exists ix_payments_org_date on public.ws_tblpayments(orgid, paymentdate desc);
create index if not exists ix_payments_customer on public.ws_tblpayments(orgid, customerid, paymentdate);

-- ─── Delivery total recalculation ────────────────────────────────────────────

-- ws.internal_recalc is the flag that lets recalc_delivery() write the derived
-- columns that tg_delivery_seal() otherwise pins. Without it the seal trigger
-- silently reverts every recalculation and the card reads all zeros — which is
-- exactly the failure this project already had in a different form.
create or replace function ws.recalc_delivery(p_deliveryid bigint)
returns void
language plpgsql
set search_path = ws, public, pg_catalog
as $$
declare
  v_org        bigint;
  v_customer   bigint;
  v_date       date;
  v_defbtid    bigint;
  v_delivered  int;
  v_returned   int;
  v_amount     numeric(14,2);
  v_rate       numeric(12,2);
  v_balance    int;
begin
  select orgid, customerid, deliverydate
    into v_org, v_customer, v_date
  from public.ws_tbldeliveries where deliveryid = p_deliveryid;

  if v_org is null then
    return;
  end if;

  select bottletypeid into v_defbtid
  from public.ws_tblbottletypes where orgid = v_org and isdefault;

  -- Bottle counts are attributed to the DEFAULT bottle type for the card view;
  -- per-type detail is available from ws_tblbottletransactions.
  select
    coalesce(sum(d.deliveredqty * p.bottlesperunit)::int, 0),
    coalesce(sum(d.returnedqty  * p.bottlesperunit)::int, 0),
    coalesce(sum(d.amount), 0)
  into v_delivered, v_returned, v_amount
  from public.ws_tbldeliverydetails d
  join public.ws_tblproducts p on p.productid = d.productid
  where d.deliveryid = p_deliveryid
    and p.bottletypeid is not distinct from v_defbtid;

  -- Amount must include non-returnable lines too.
  select coalesce(sum(amount), 0) into v_amount
  from public.ws_tbldeliverydetails where deliveryid = p_deliveryid;

  select d.unitprice into v_rate
  from public.ws_tbldeliverydetails d
  join public.ws_tblproducts p on p.productid = d.productid
  where d.deliveryid = p_deliveryid and p.bottletypeid is not distinct from v_defbtid
  order by d.deliverydetailid
  limit 1;

  select coalesce(balance, 0) into v_balance
  from public.ws_tblcustomerbottlebalances
  where customerid = v_customer and bottletypeid = v_defbtid;

  perform set_config('ws.internal_recalc', '1', true);

  update public.ws_tbldeliveries
     set bottlesdelivered = v_delivered,
         bottlesreturned  = v_returned,
         amountcharged    = v_amount,
         rateapplied      = coalesce(v_rate, 0),
         bottlebalance    = coalesce(v_balance, 0),
         updated_at       = now()
   where deliveryid = p_deliveryid;

  perform set_config('ws.internal_recalc', '', true);
end
$$;

-- Line items: price defaults from ws.resolve_price(), amount is always derived.
create or replace function ws.tg_deliverydetail_prepare()
returns trigger
language plpgsql
set search_path = ws, public, pg_catalog
as $$
declare
  v_org      bigint;
  v_customer bigint;
  v_date     date;
  v_prodorg  bigint;
begin
  select orgid, customerid, deliverydate
    into v_org, v_customer, v_date
  from public.ws_tbldeliveries where deliveryid = new.deliveryid;

  new.orgid := v_org;

  select orgid into v_prodorg from public.ws_tblproducts where productid = new.productid;
  perform ws.assert_same_org(v_org, v_prodorg, 'delivery detail vs product');

  if new.unitprice is null or new.unitprice = 0 then
    new.unitprice := ws.resolve_price(v_org, new.productid, v_customer, v_date);
  end if;

  new.amount := round(new.deliveredqty * new.unitprice, 2);
  return new;
end
$$;

drop trigger if exists trg_deliverydetail_prepare on public.ws_tbldeliverydetails;
create trigger trg_deliverydetail_prepare
  before insert or update on public.ws_tbldeliverydetails
  for each row execute function ws.tg_deliverydetail_prepare();

-- Move bottles for the line, then refresh header totals and re-post the journal.
create or replace function ws.tg_deliverydetail_after()
returns trigger
language plpgsql
set search_path = ws, public, pg_catalog
as $$
declare
  r record;
  v_org        bigint;
  v_customer   bigint;
  v_date       date;
  v_bottletype bigint;
  v_per        int;
  v_out        int;
  v_in         int;
begin
  r := coalesce(new, old);

  select d.orgid, d.customerid, d.deliverydate
    into v_org, v_customer, v_date
  from public.ws_tbldeliveries d where d.deliveryid = r.deliveryid;

  if v_org is null then
    return null;   -- header being deleted; cascade will clean up
  end if;

  select p.bottletypeid, p.bottlesperunit into v_bottletype, v_per
  from public.ws_tblproducts p where p.productid = r.productid;

  if tg_op = 'INSERT' and v_bottletype is not null and v_per > 0 then
    v_out := (new.deliveredqty * v_per)::int;
    v_in  := (new.returnedqty  * v_per)::int;

    if v_out <> 0 then
      insert into public.ws_tblbottletransactions
        (orgid, customerid, bottletypeid, deliveryid, txndate, txntype, qty, balancebefore, balanceafter, createdby)
      values (v_org, v_customer, v_bottletype, r.deliveryid, v_date, 'delivery', v_out, 0, 0, ws.current_uid());
    end if;

    if v_in <> 0 then
      insert into public.ws_tblbottletransactions
        (orgid, customerid, bottletypeid, deliveryid, txndate, txntype, qty, balancebefore, balanceafter, createdby)
      values (v_org, v_customer, v_bottletype, r.deliveryid, v_date, 'return', -v_in, 0, 0, ws.current_uid());
    end if;
  end if;

  perform ws.recalc_delivery(r.deliveryid);
  perform ws.post_delivery(r.deliveryid);
  return null;
end
$$;

drop trigger if exists trg_deliverydetail_after on public.ws_tbldeliverydetails;
create trigger trg_deliverydetail_after
  after insert or update or delete on public.ws_tbldeliverydetails
  for each row execute function ws.tg_deliverydetail_after();

-- Header: assign a reference number, block client writes to derived columns.
create or replace function ws.tg_delivery_seal()
returns trigger
language plpgsql
set search_path = ws, public, pg_catalog
as $$
declare
  v_custorg bigint;
begin
  if tg_op = 'INSERT' then
    select orgid into v_custorg from public.ws_tblcustomers where customerid = new.customerid;
    perform ws.assert_same_org(new.orgid, v_custorg, 'delivery vs customer');

    if new.referenceno is null then
      new.referenceno := ws.next_docnumber(new.orgid, 'delivery');
    end if;
    new.createdby := coalesce(new.createdby, ws.current_uid());
    -- Derived columns start at zero regardless of what the client sent.
    new.bottlesdelivered := 0;
    new.bottlesreturned  := 0;
    new.bottlebalance    := 0;
    new.rateapplied      := 0;
    new.amountcharged    := 0;
  elsif coalesce(current_setting('ws.internal_recalc', true), '') <> '1' then
    -- Preserve derived columns on client updates; only recalc_delivery may
    -- change them, and it announces itself with ws.internal_recalc.
    new.bottlesdelivered := old.bottlesdelivered;
    new.bottlesreturned  := old.bottlesreturned;
    new.bottlebalance    := old.bottlebalance;
    new.rateapplied      := old.rateapplied;
    new.amountcharged    := old.amountcharged;
    new.updated_at       := now();
  end if;
  return new;
end
$$;

drop trigger if exists trg_delivery_seal on public.ws_tbldeliveries;
create trigger trg_delivery_seal
  before insert or update on public.ws_tbldeliveries
  for each row execute function ws.tg_delivery_seal();

-- ─── Journal posting: sale ───────────────────────────────────────────────────
-- Runs inside the caller's transaction. Debit AR, credit Sales.

create or replace function ws.post_delivery(p_deliveryid bigint)
returns void
language plpgsql
set search_path = ws, public, pg_catalog
as $$
declare
  v_org      bigint;
  v_customer bigint;
  v_date     date;
  v_amount   numeric(14,2);
  v_void     boolean;
  v_ref      text;
  v_j        bigint;
begin
  select orgid, customerid, deliverydate, amountcharged, isvoid, referenceno
    into v_org, v_customer, v_date, v_amount, v_void, v_ref
  from public.ws_tbldeliveries where deliveryid = p_deliveryid;

  if v_org is null then
    return;
  end if;

  if v_void or coalesce(v_amount, 0) = 0 then
    delete from public.ws_tbljournalentries
    where orgid = v_org and sourcetype = 'sale' and sourceid = p_deliveryid;
    return;
  end if;

  v_j := ws.journal_upsert_header(v_org, 'sale', p_deliveryid, v_date,
                                  'Delivery ' || coalesce(v_ref, p_deliveryid::text));

  perform ws.journal_line(v_j, v_org, ws.account_by_control(v_org, 'ar'),
                          v_amount, 0, v_customer, null, 'Water delivery');
  perform ws.journal_line(v_j, v_org, ws.account_by_code(v_org, '4000'),
                          0, v_amount, v_customer, null, 'Water sales');
end
$$;

create or replace function ws.tg_delivery_after()
returns trigger
language plpgsql
set search_path = ws, public, pg_catalog
as $$
begin
  perform ws.post_delivery(new.deliveryid);
  return null;
end
$$;

drop trigger if exists trg_delivery_after on public.ws_tbldeliveries;
create trigger trg_delivery_after
  after update of isvoid, deliverydate on public.ws_tbldeliveries
  for each row execute function ws.tg_delivery_after();

-- ─── Journal posting: customer payment ───────────────────────────────────────
-- Debit Cash/Bank (per payment method), credit AR.

create or replace function ws.post_customer_payment(p_paymentid bigint)
returns void
language plpgsql
set search_path = ws, public, pg_catalog
as $$
declare
  v_org      bigint;
  v_customer bigint;
  v_date     date;
  v_amount   numeric(14,2);
  v_void     boolean;
  v_methodid bigint;
  v_method   text;
  v_acct     bigint;
  v_receipt  text;
  v_j        bigint;
begin
  select orgid, customerid, paymentdate, amountreceived, isvoid, methodid, paymentmethod, receiptno
    into v_org, v_customer, v_date, v_amount, v_void, v_methodid, v_method, v_receipt
  from public.ws_tblpayments where paymentid = p_paymentid;

  if v_org is null then
    return;
  end if;

  if v_void then
    delete from public.ws_tbljournalentries
    where orgid = v_org and sourcetype = 'customerpayment' and sourceid = p_paymentid;
    return;
  end if;

  -- Settlement account: explicit method, else the legacy text column, else cash.
  select accountid into v_acct
  from public.ws_tblpaymentmethods
  where (methodid = v_methodid)
     or (v_methodid is null and orgid = v_org and methodcode = coalesce(v_method,'cash'))
  order by (methodid = v_methodid) desc
  limit 1;

  v_acct := coalesce(v_acct, ws.account_by_control(v_org, 'cash'));

  v_j := ws.journal_upsert_header(v_org, 'customerpayment', p_paymentid, v_date,
                                  'Receipt ' || coalesce(v_receipt, p_paymentid::text));

  perform ws.journal_line(v_j, v_org, v_acct, v_amount, 0, v_customer, null, 'Cash received');
  perform ws.journal_line(v_j, v_org, ws.account_by_control(v_org, 'ar'),
                          0, v_amount, v_customer, null, 'Customer payment');
end
$$;

create or replace function ws.tg_payment_before()
returns trigger
language plpgsql
set search_path = ws, public, pg_catalog
as $$
declare v_custorg bigint;
begin
  if tg_op = 'INSERT' then
    select orgid into v_custorg from public.ws_tblcustomers where customerid = new.customerid;
    perform ws.assert_same_org(new.orgid, v_custorg, 'payment vs customer');
    if new.receiptno is null then
      new.receiptno := ws.next_docnumber(new.orgid, 'receipt');
    end if;
    new.createdby := coalesce(new.createdby, ws.current_uid());
  end if;
  return new;
end
$$;

drop trigger if exists trg_payment_before on public.ws_tblpayments;
create trigger trg_payment_before
  before insert or update on public.ws_tblpayments
  for each row execute function ws.tg_payment_before();

create or replace function ws.tg_payment_after()
returns trigger
language plpgsql
set search_path = ws, public, pg_catalog
as $$
begin
  perform ws.post_customer_payment(new.paymentid);
  return null;
end
$$;

drop trigger if exists trg_payment_after on public.ws_tblpayments;
create trigger trg_payment_after
  after insert or update on public.ws_tblpayments
  for each row execute function ws.tg_payment_after();

-- ─── Opening balances ────────────────────────────────────────────────────────
-- A customer's opening money balance and opening bottle balance must both enter
-- the system as transactions, otherwise the ledger does not tie to the journal.

create or replace function public.ws_set_customer_opening(
  p_customerid   bigint,
  p_openingdue   numeric default 0,
  p_bottletypeid bigint  default null,
  p_openingqty   int     default 0,
  p_asof         date    default current_date
)
returns void
language plpgsql
security definer
set search_path = ws, public, pg_catalog
as $$
declare
  v_org bigint;
  v_bt  bigint;
  v_j   bigint;
begin
  select orgid into v_org from public.ws_tblcustomers where customerid = p_customerid;
  if v_org is null then
    raise exception 'customer % not found', p_customerid using errcode = 'P0002';
  end if;
  if not ws.has_perm(v_org, 'customers.manage') then
    raise exception 'permission denied: customers.manage' using errcode = '42501';
  end if;

  update public.ws_tblcustomers set openingbalance = p_openingdue where customerid = p_customerid;

  if coalesce(p_openingdue, 0) <> 0 then
    v_j := ws.journal_upsert_header(v_org, 'opening', p_customerid, p_asof,
             'Opening balance for customer ' || p_customerid);
    perform ws.journal_line(v_j, v_org, ws.account_by_control(v_org, 'ar'),
                            p_openingdue, 0, p_customerid, null, 'Opening receivable');
    perform ws.journal_line(v_j, v_org, ws.account_by_code(v_org, '3900'),
                            0, p_openingdue, p_customerid, null, 'Opening balance equity');
  end if;

  v_bt := coalesce(p_bottletypeid,
                   (select bottletypeid from public.ws_tblbottletypes where orgid = v_org and isdefault));

  if v_bt is not null and coalesce(p_openingqty, 0) <> 0 then
    insert into public.ws_tblbottletransactions
      (orgid, customerid, bottletypeid, txndate, txntype, qty, balancebefore, balanceafter, notes, createdby)
    values
      (v_org, p_customerid, v_bt, p_asof, 'opening', p_openingqty, 0, 0, 'Opening bottle balance', ws.current_uid());
  end if;
end
$$;

revoke all on function public.ws_set_customer_opening(bigint,numeric,bigint,int,date) from public;
grant execute on function public.ws_set_customer_opening(bigint,numeric,bigint,int,date) to authenticated;

-- ─── The one call the delivery screen needs ──────────────────────────────────
-- Mirrors the paper card exactly: delivered, received, and money taken, in one
-- atomic transaction. Replaces the current two-step client sequence in
-- delivery_screen.dart, where the payment insert can fail after the delivery
-- has already been committed.

create or replace function public.ws_record_delivery(
  p_customerid    bigint,
  p_deliverydate  date    default current_date,
  p_delivered     int     default 0,
  p_returned      int     default 0,
  p_productid     bigint  default null,
  p_amountpaid    numeric default 0,
  p_paymentmethod text    default 'cash',
  p_deliveredbyid bigint  default null,
  p_routeid       bigint  default null,
  p_notes         text    default null
)
returns bigint
language plpgsql
security definer
set search_path = ws, public, pg_catalog
as $$
declare
  v_org        bigint;
  v_product    bigint;
  v_deliveryid bigint;
  v_methodid   bigint;
begin
  select orgid into v_org from public.ws_tblcustomers where customerid = p_customerid;
  if v_org is null then
    raise exception 'customer % not found', p_customerid using errcode = 'P0002';
  end if;
  if not ws.has_perm(v_org, 'delivery.manage') then
    raise exception 'permission denied: delivery.manage' using errcode = '42501';
  end if;

  -- Default product = the cheapest-to-guess correct thing: the org's returnable
  -- water product on the default bottle type.
  v_product := p_productid;
  if v_product is null then
    select p.productid into v_product
    from public.ws_tblproducts p
    join public.ws_tblbottletypes b on b.bottletypeid = p.bottletypeid
    where p.orgid = v_org and p.isactive and b.isdefault
    order by p.productid
    limit 1;
  end if;

  if v_product is null then
    raise exception 'org % has no returnable product configured on its default bottle type', v_org
      using errcode = 'P0002';
  end if;

  insert into public.ws_tbldeliveries
    (orgid, customerid, routeid, deliveredbyid, deliverydate, notes)
  values
    (v_org, p_customerid, p_routeid, p_deliveredbyid, p_deliverydate, p_notes)
  returning deliveryid into v_deliveryid;

  insert into public.ws_tbldeliverydetails
    (deliveryid, orgid, productid, deliveredqty, returnedqty)
  values
    (v_deliveryid, v_org, v_product, p_delivered, p_returned);

  if coalesce(p_amountpaid, 0) > 0 then
    select methodid into v_methodid
    from public.ws_tblpaymentmethods
    where orgid = v_org and methodcode = coalesce(p_paymentmethod, 'cash');

    insert into public.ws_tblpayments
      (orgid, customerid, deliveryid, receivedbyid, methodid, paymentdate,
       amountreceived, paymentmethod)
    values
      (v_org, p_customerid, v_deliveryid, p_deliveredbyid, v_methodid, p_deliverydate,
       p_amountpaid, coalesce(p_paymentmethod, 'cash'));
  end if;

  return v_deliveryid;
end
$$;

revoke all on function public.ws_record_delivery(bigint,date,int,int,bigint,numeric,text,bigint,bigint,text) from public;
grant execute on function public.ws_record_delivery(bigint,date,int,int,bigint,numeric,text,bigint,bigint,text) to authenticated;

-- ─── Cache rebuild (run after a bulk import or to prove the cache is honest) ──

create or replace function public.ws_rebuild_bottle_balances(p_orgid bigint)
returns int
language plpgsql
security definer
set search_path = ws, public, pg_catalog
as $$
declare v_rows int;
begin
  if not ws.has_perm(p_orgid, 'org.manage') then
    raise exception 'permission denied: org.manage' using errcode = '42501';
  end if;

  with truth as (
    select orgid, customerid, bottletypeid, sum(qty)::int as balance
    from public.ws_tblbottletransactions
    where orgid = p_orgid and customerid is not null
    group by orgid, customerid, bottletypeid
  )
  insert into public.ws_tblcustomerbottlebalances (orgid, customerid, bottletypeid, balance)
  select orgid, customerid, bottletypeid, balance from truth
  on conflict (customerid, bottletypeid)
  do update set balance = excluded.balance, updated_at = now();

  get diagnostics v_rows = row_count;

  update public.ws_tblcustomers c
     set bottlebalance = coalesce(b.balance, 0)
  from public.ws_tblbottletypes t
  left join public.ws_tblcustomerbottlebalances b
         on b.bottletypeid = t.bottletypeid and b.customerid = c.customerid
  where t.orgid = p_orgid and t.isdefault and c.orgid = p_orgid;

  return v_rows;
end
$$;

revoke all on function public.ws_rebuild_bottle_balances(bigint) from public;
grant execute on function public.ws_rebuild_bottle_balances(bigint) to authenticated;
