-- =============================================================================
-- 006_vendor_operations.sql
-- Purchases and vendor payments, with the same in-transaction posting rules.
-- =============================================================================

create table if not exists public.ws_tblpurchases (
  purchaseid   bigint generated by default as identity primary key,
  orgid        bigint not null references public.ws_tblorganization(orgid) on delete cascade,
  vendorid     bigint not null references public.ws_tblvendors(vendorid) on delete restrict,
  purchasedate date   not null default current_date,
  billno       text,
  referenceno  text,
  notes        text,
  totalamount  numeric(14,2) not null default 0,   -- trigger-maintained
  isvoid       boolean not null default false,
  createdby    uuid   references auth.users(id) on delete set null,
  createddate  timestamptz not null default now(),
  unique (orgid, referenceno)
);

create index if not exists ix_purchases_org_date on public.ws_tblpurchases(orgid, purchasedate desc);
create index if not exists ix_purchases_vendor   on public.ws_tblpurchases(orgid, vendorid, purchasedate);

create table if not exists public.ws_tblpurchasedetails (
  purchasedetailid bigint generated by default as identity primary key,
  purchaseid       bigint not null references public.ws_tblpurchases(purchaseid) on delete cascade,
  orgid            bigint not null references public.ws_tblorganization(orgid) on delete cascade,
  productid        bigint not null references public.ws_tblproducts(productid) on delete restrict,
  quantity         numeric(12,2) not null check (quantity > 0),
  unitcost         numeric(12,2) not null default 0 check (unitcost >= 0),
  amount           numeric(14,2) not null default 0,
  notes            text
);

create index if not exists ix_purchasedetails_purchase on public.ws_tblpurchasedetails(purchaseid);

create table if not exists public.ws_tblvendorpayments (
  vendorpaymentid bigint generated by default as identity primary key,
  orgid           bigint not null references public.ws_tblorganization(orgid) on delete cascade,
  vendorid        bigint not null references public.ws_tblvendors(vendorid) on delete restrict,
  purchaseid      bigint references public.ws_tblpurchases(purchaseid) on delete set null,
  methodid        bigint references public.ws_tblpaymentmethods(methodid) on delete set null,
  paiddate        date   not null default current_date,
  amountpaid      numeric(14,2) not null check (amountpaid > 0),
  voucherno       text,
  referenceno     text,
  notes           text,
  isvoid          boolean not null default false,
  createdby       uuid   references auth.users(id) on delete set null,
  createddate     timestamptz not null default now(),
  unique (orgid, voucherno)
);

create index if not exists ix_vendorpayments_vendor on public.ws_tblvendorpayments(orgid, vendorid, paiddate);

-- ─── Purchase line preparation and stock-side bottle movement ────────────────

create or replace function ws.tg_purchasedetail_prepare()
returns trigger
language plpgsql
set search_path = ws, public, pg_catalog
as $$
declare
  v_org     bigint;
  v_prodorg bigint;
begin
  select orgid into v_org from public.ws_tblpurchases where purchaseid = new.purchaseid;
  new.orgid := v_org;

  select orgid into v_prodorg from public.ws_tblproducts where productid = new.productid;
  perform ws.assert_same_org(v_org, v_prodorg, 'purchase detail vs product');

  if new.unitcost is null or new.unitcost = 0 then
    select purchaseprice into new.unitcost
    from public.ws_tblproducts where productid = new.productid;
  end if;

  new.amount := round(new.quantity * coalesce(new.unitcost, 0), 2);
  return new;
end
$$;

drop trigger if exists trg_purchasedetail_prepare on public.ws_tblpurchasedetails;
create trigger trg_purchasedetail_prepare
  before insert or update on public.ws_tblpurchasedetails
  for each row execute function ws.tg_purchasedetail_prepare();

create or replace function ws.recalc_purchase(p_purchaseid bigint)
returns void
language plpgsql
set search_path = ws, public, pg_catalog
as $$
begin
  perform set_config('ws.internal_recalc', '1', true);

  update public.ws_tblpurchases p
     set totalamount = coalesce((
           select sum(d.amount) from public.ws_tblpurchasedetails d
           where d.purchaseid = p_purchaseid
         ), 0)
   where p.purchaseid = p_purchaseid;

  perform set_config('ws.internal_recalc', '', true);
end
$$;

-- Buying empty bottles increases the stock side, not any customer's balance.
-- Recorded with customerid = NULL so the bottle ledger stays complete.
create or replace function ws.tg_purchasedetail_after()
returns trigger
language plpgsql
set search_path = ws, public, pg_catalog
as $$
declare
  r            record;
  v_org        bigint;
  v_date       date;
  v_bottletype bigint;
  v_per        int;
begin
  r := coalesce(new, old);

  select orgid, purchasedate into v_org, v_date
  from public.ws_tblpurchases where purchaseid = r.purchaseid;

  if v_org is null then
    return null;
  end if;

  if tg_op = 'INSERT' then
    select bottletypeid, bottlesperunit into v_bottletype, v_per
    from public.ws_tblproducts where productid = r.productid;

    if v_bottletype is not null and v_per > 0 then
      insert into public.ws_tblbottletransactions
        (orgid, customerid, bottletypeid, txndate, txntype, qty, balancebefore, balanceafter, notes, createdby)
      values
        (v_org, null, v_bottletype, v_date, 'adjustment',
         (new.quantity * v_per)::int, 0, 0, 'Bottles purchased into stock', ws.current_uid());
    end if;
  end if;

  perform ws.recalc_purchase(r.purchaseid);
  perform ws.post_purchase(r.purchaseid);
  return null;
end
$$;

drop trigger if exists trg_purchasedetail_after on public.ws_tblpurchasedetails;
create trigger trg_purchasedetail_after
  after insert or update or delete on public.ws_tblpurchasedetails
  for each row execute function ws.tg_purchasedetail_after();

-- ─── Journal posting: purchase (Inventory DR / AP CR) ────────────────────────

create or replace function ws.post_purchase(p_purchaseid bigint)
returns void
language plpgsql
set search_path = ws, public, pg_catalog
as $$
declare
  v_org    bigint;
  v_vendor bigint;
  v_date   date;
  v_amount numeric(14,2);
  v_void   boolean;
  v_ref    text;
  v_j      bigint;
begin
  select orgid, vendorid, purchasedate, totalamount, isvoid, coalesce(billno, referenceno)
    into v_org, v_vendor, v_date, v_amount, v_void, v_ref
  from public.ws_tblpurchases where purchaseid = p_purchaseid;

  if v_org is null then
    return;
  end if;

  if v_void or coalesce(v_amount, 0) = 0 then
    delete from public.ws_tbljournalentries
    where orgid = v_org and sourcetype = 'purchase' and sourceid = p_purchaseid;
    return;
  end if;

  v_j := ws.journal_upsert_header(v_org, 'purchase', p_purchaseid, v_date,
                                  'Purchase ' || coalesce(v_ref, p_purchaseid::text));

  perform ws.journal_line(v_j, v_org, ws.account_by_control(v_org, 'inventory'),
                          v_amount, 0, null, v_vendor, 'Inventory purchased');
  perform ws.journal_line(v_j, v_org, ws.account_by_control(v_org, 'ap'),
                          0, v_amount, null, v_vendor, 'Vendor payable');
end
$$;

create or replace function ws.tg_purchase_before()
returns trigger
language plpgsql
set search_path = ws, public, pg_catalog
as $$
declare v_vorg bigint;
begin
  if tg_op = 'INSERT' then
    select orgid into v_vorg from public.ws_tblvendors where vendorid = new.vendorid;
    perform ws.assert_same_org(new.orgid, v_vorg, 'purchase vs vendor');
    if new.referenceno is null then
      new.referenceno := ws.next_docnumber(new.orgid, 'purchase');
    end if;
    new.createdby := coalesce(new.createdby, ws.current_uid());
    new.totalamount := 0;
  elsif coalesce(current_setting('ws.internal_recalc', true), '') <> '1' then
    new.totalamount := old.totalamount;
  end if;
  return new;
end
$$;

drop trigger if exists trg_purchase_before on public.ws_tblpurchases;
create trigger trg_purchase_before
  before insert or update on public.ws_tblpurchases
  for each row execute function ws.tg_purchase_before();

create or replace function ws.tg_purchase_after()
returns trigger
language plpgsql
set search_path = ws, public, pg_catalog
as $$
begin
  perform ws.post_purchase(new.purchaseid);
  return null;
end
$$;

drop trigger if exists trg_purchase_after on public.ws_tblpurchases;
create trigger trg_purchase_after
  after update of isvoid, purchasedate on public.ws_tblpurchases
  for each row execute function ws.tg_purchase_after();

-- ─── Journal posting: vendor payment (AP DR / Cash CR) ───────────────────────

create or replace function ws.post_vendor_payment(p_vendorpaymentid bigint)
returns void
language plpgsql
set search_path = ws, public, pg_catalog
as $$
declare
  v_org    bigint;
  v_vendor bigint;
  v_date   date;
  v_amount numeric(14,2);
  v_void   boolean;
  v_method bigint;
  v_acct   bigint;
  v_ref    text;
  v_j      bigint;
begin
  select orgid, vendorid, paiddate, amountpaid, isvoid, methodid, coalesce(voucherno, referenceno)
    into v_org, v_vendor, v_date, v_amount, v_void, v_method, v_ref
  from public.ws_tblvendorpayments where vendorpaymentid = p_vendorpaymentid;

  if v_org is null then
    return;
  end if;

  if v_void then
    delete from public.ws_tbljournalentries
    where orgid = v_org and sourcetype = 'vendorpayment' and sourceid = p_vendorpaymentid;
    return;
  end if;

  select accountid into v_acct from public.ws_tblpaymentmethods where methodid = v_method;
  v_acct := coalesce(v_acct, ws.account_by_control(v_org, 'cash'));

  v_j := ws.journal_upsert_header(v_org, 'vendorpayment', p_vendorpaymentid, v_date,
                                  'Vendor payment ' || coalesce(v_ref, p_vendorpaymentid::text));

  perform ws.journal_line(v_j, v_org, ws.account_by_control(v_org, 'ap'),
                          v_amount, 0, null, v_vendor, 'Paid to vendor');
  perform ws.journal_line(v_j, v_org, v_acct, 0, v_amount, null, v_vendor, 'Cash paid out');
end
$$;

create or replace function ws.tg_vendorpayment_before()
returns trigger
language plpgsql
set search_path = ws, public, pg_catalog
as $$
declare v_vorg bigint;
begin
  if tg_op = 'INSERT' then
    select orgid into v_vorg from public.ws_tblvendors where vendorid = new.vendorid;
    perform ws.assert_same_org(new.orgid, v_vorg, 'vendor payment vs vendor');
    if new.voucherno is null then
      new.voucherno := ws.next_docnumber(new.orgid, 'vendorpayment');
    end if;
    new.createdby := coalesce(new.createdby, ws.current_uid());
  end if;
  return new;
end
$$;

drop trigger if exists trg_vendorpayment_before on public.ws_tblvendorpayments;
create trigger trg_vendorpayment_before
  before insert or update on public.ws_tblvendorpayments
  for each row execute function ws.tg_vendorpayment_before();

create or replace function ws.tg_vendorpayment_after()
returns trigger
language plpgsql
set search_path = ws, public, pg_catalog
as $$
begin
  perform ws.post_vendor_payment(new.vendorpaymentid);
  return null;
end
$$;

drop trigger if exists trg_vendorpayment_after on public.ws_tblvendorpayments;
create trigger trg_vendorpayment_after
  after insert or update on public.ws_tblvendorpayments
  for each row execute function ws.tg_vendorpayment_after();

-- ─── Vendor opening balance ──────────────────────────────────────────────────

create or replace function public.ws_set_vendor_opening(
  p_vendorid bigint,
  p_opening  numeric default 0,
  p_asof     date default current_date
)
returns void
language plpgsql
security definer
set search_path = ws, public, pg_catalog
as $$
declare
  v_org bigint;
  v_j   bigint;
begin
  select orgid into v_org from public.ws_tblvendors where vendorid = p_vendorid;
  if v_org is null then
    raise exception 'vendor % not found', p_vendorid using errcode = 'P0002';
  end if;
  if not ws.has_perm(v_org, 'vendors.manage') then
    raise exception 'permission denied: vendors.manage' using errcode = '42501';
  end if;

  update public.ws_tblvendors set openingbalance = p_opening where vendorid = p_vendorid;

  if coalesce(p_opening, 0) <> 0 then
    -- Negative sourceid keyspace keeps vendor openings from colliding with the
    -- customer openings that share sourcetype 'opening'.
    v_j := ws.journal_upsert_header(v_org, 'opening', -p_vendorid, p_asof,
             'Opening balance for vendor ' || p_vendorid);
    perform ws.journal_line(v_j, v_org, ws.account_by_code(v_org, '3900'),
                            p_opening, 0, null, p_vendorid, 'Opening balance equity');
    perform ws.journal_line(v_j, v_org, ws.account_by_control(v_org, 'ap'),
                            0, p_opening, null, p_vendorid, 'Opening payable');
  end if;
end
$$;

revoke all on function public.ws_set_vendor_opening(bigint,numeric,date) from public;
grant execute on function public.ws_set_vendor_opening(bigint,numeric,date) to authenticated;
