-- =============================================================================
-- 014_idempotent_master_data.sql
-- Closes the last three duplicate-on-retry paths: customers, vendors, and
-- organization registration.
--
-- ─── WHY THESE THREE ARE NOT "JUST MASTER DATA" ──────────────────────────────
--
-- A duplicate customer is a SPLIT LEDGER. bottlebalance, depositamount,
-- openingbalance and outstanding due are all keyed on customerid. If a save
-- times out after committing and the user taps Save again, the deliveries
-- recorded before the retry hang off one row and everything after hangs off
-- the other. The customer's bottle count is wrong, their statement is wrong,
-- and — the part that matters most — vw_ws_reconciliation STILL RETURNS 0,
-- because both halves are summed into the same totals. The one automated check
-- that guards the books cannot see this class of damage. The same argument
-- applies to vendors and payables.
--
-- A duplicate organization is worse in a different way: the user lands in a
-- tenant with no data, or picks between two identical names forever.
--
-- ─── THE MECHANISM IS THE ONE ALREADY PROVEN ─────────────────────────────────
--
-- Identical to migrations 010/012/013: a client-generated uuid, a PARTIAL
-- unique index that ignores the rows written before this existed, and an
-- early-return inside a SECURITY DEFINER function so a retry is a READ.
--
-- FIRST WRITE WINS. A retry returns the original id and ignores its own
-- payload, so a tampered or half-edited second attempt cannot mutate a record
-- that already exists.
--
-- Deliberately NOT used as the key: customercode, vendorcode, customername,
-- vendorname. Those are nullable or user-editable. An idempotency key must be
-- meaningless, mandatory and generated by the client — the moment it doubles
-- as business data, the user can change it and break the guarantee.
--
-- ─── WHAT IS NOT CHANGED ─────────────────────────────────────────────────────
--
--   · No business logic. The RPCs insert exactly the columns the client
--     already inserted, in the same way.
--   · No accounting. None of these three tables posts a journal entry on
--     insert, and this migration does not add one.
--   · No document numbering. customercode / vendorcode / publicid keep their
--     existing behaviour; publicid still comes from its column default.
--   · The direct-insert paths still work. clientuuid is nullable and the index
--     is partial, so every existing row and every legacy caller stays valid.
--   · ws.seed_chart_of_accounts is untouched and still idempotent.
--
-- PURELY ADDITIVE: three nullable columns, three partial indexes, two new
-- functions, two functions gaining one defaulted parameter, one lookup
-- extended. No data migration. Safe to re-run.
-- =============================================================================


-- ═════════════════════════════════════════════════════════════════════════════
-- 1. CUSTOMERS
-- ═════════════════════════════════════════════════════════════════════════════

alter table public.ws_tblcustomers
  add column if not exists clientuuid uuid;

comment on column public.ws_tblcustomers.clientuuid is
  'Client-generated idempotency key for the create path. A retry after a lost '
  'response returns the existing customerid instead of splitting the '
  'customer''s ledger across two rows.';

-- PARTIAL: every customer created before this migration has a null key, and
-- there may be any number of those.
create unique index if not exists ux_customer_clientuuid
  on public.ws_tblcustomers(orgid, clientuuid)
  where clientuuid is not null;


create or replace function public.ws_record_customer(
  p_orgid         bigint,
  p_customername  text,
  p_areaid        bigint  default null,
  p_customercode  text    default null,
  p_contactperson text    default null,
  p_phone         text    default null,
  p_email         text    default null,
  p_address       text    default null,
  p_rateoverride  numeric default null,
  p_depositamount numeric default 0,
  p_routeid       bigint  default null,
  p_groupid       bigint  default null,
  p_openingbalance numeric default 0,
  p_clientuuid    uuid    default null
)
returns bigint
language plpgsql
security definer
set search_path = ws, public, pg_catalog
as $$
declare
  v_customerid bigint;
  v_areaorg    bigint;
begin
  if not ws.has_perm(p_orgid, 'customers.manage') then
    raise exception 'permission denied: customers.manage' using errcode = '42501';
  end if;

  -- ── IDEMPOTENCY CHECK, BEFORE ANYTHING IS WRITTEN ──────────────────────
  -- A retry lands here and leaves as a read. Note it returns WITHOUT looking
  -- at the rest of the payload: first write wins, so a second attempt that
  -- carries edited fields cannot overwrite the record that already exists.
  if p_clientuuid is not null then
    select customerid into v_customerid
    from public.ws_tblcustomers
    where orgid = p_orgid and clientuuid = p_clientuuid;

    if v_customerid is not null then
      return v_customerid;
    end if;
  end if;

  -- ── VALIDATE ───────────────────────────────────────────────────────────
  if coalesce(trim(p_customername), '') = '' then
    raise exception 'customer name is required' using errcode = '22023';
  end if;

  -- An area belonging to another tenant would otherwise be accepted and only
  -- surface later as a customer whose rate cannot be resolved.
  if p_areaid is not null then
    select orgid into v_areaorg from public.ws_tblareas where areaid = p_areaid;
    if v_areaorg is null then
      raise exception 'area % not found', p_areaid using errcode = 'P0002';
    end if;
    perform ws.assert_same_org(p_orgid, v_areaorg, 'customer vs area');
  end if;

  -- ── WRITE ──────────────────────────────────────────────────────────────
  -- The same columns the client insert wrote, nothing more. bottlebalance is
  -- deliberately absent: it is a trigger-maintained cache.
  insert into public.ws_tblcustomers
    (orgid, customername, customercode, areaid, routeid, groupid,
     contactperson, phone, email, address, rateoverride, depositamount,
     openingbalance, clientuuid)
  values
    (p_orgid, p_customername, p_customercode, p_areaid, p_routeid, p_groupid,
     p_contactperson, p_phone, p_email, p_address, p_rateoverride,
     coalesce(p_depositamount, 0), coalesce(p_openingbalance, 0), p_clientuuid)
  returning customerid into v_customerid;

  return v_customerid;
end
$$;

revoke all on function public.ws_record_customer(
  bigint,text,bigint,text,text,text,text,text,numeric,numeric,bigint,bigint,
  numeric,uuid) from public;
grant execute on function public.ws_record_customer(
  bigint,text,bigint,text,text,text,text,text,numeric,numeric,bigint,bigint,
  numeric,uuid) to authenticated;


-- ═════════════════════════════════════════════════════════════════════════════
-- 2. VENDORS
-- ═════════════════════════════════════════════════════════════════════════════

alter table public.ws_tblvendors
  add column if not exists clientuuid uuid;

comment on column public.ws_tblvendors.clientuuid is
  'Client-generated idempotency key for the create path. Prevents a retry '
  'after a lost response from splitting payables across two vendor rows.';

create unique index if not exists ux_vendor_clientuuid
  on public.ws_tblvendors(orgid, clientuuid)
  where clientuuid is not null;


create or replace function public.ws_record_vendor(
  p_orgid          bigint,
  p_vendorname     text,
  p_vendorcode     text    default null,
  p_contactperson  text    default null,
  p_phone          text    default null,
  p_email          text    default null,
  p_address        text    default null,
  p_openingbalance numeric default 0,
  p_clientuuid     uuid    default null
)
returns bigint
language plpgsql
security definer
set search_path = ws, public, pg_catalog
as $$
declare
  v_vendorid bigint;
begin
  if not ws.has_perm(p_orgid, 'vendors.manage') then
    raise exception 'permission denied: vendors.manage' using errcode = '42501';
  end if;

  -- First write wins. See ws_record_customer.
  if p_clientuuid is not null then
    select vendorid into v_vendorid
    from public.ws_tblvendors
    where orgid = p_orgid and clientuuid = p_clientuuid;

    if v_vendorid is not null then
      return v_vendorid;
    end if;
  end if;

  if coalesce(trim(p_vendorname), '') = '' then
    raise exception 'vendor name is required' using errcode = '22023';
  end if;

  -- p_openingbalance is written RAW, exactly as the client insert wrote it.
  --
  -- That is deliberate preservation, not endorsement: a non-zero opening
  -- balance set this way has no matching journal entry, so the AP subsidiary
  -- and the general ledger disagree. That behaviour predates this migration
  -- and ws.set_vendor_opening() is the path that posts the entry. Changing it
  -- here would be an accounting change, which is out of scope for a migration
  -- about idempotency.
  insert into public.ws_tblvendors
    (orgid, vendorname, vendorcode, contactperson, phone, email, address,
     openingbalance, clientuuid)
  values
    (p_orgid, p_vendorname, p_vendorcode, p_contactperson, p_phone, p_email,
     p_address, coalesce(p_openingbalance, 0), p_clientuuid)
  returning vendorid into v_vendorid;

  return v_vendorid;
end
$$;

revoke all on function public.ws_record_vendor(
  bigint,text,text,text,text,text,text,numeric,uuid) from public;
grant execute on function public.ws_record_vendor(
  bigint,text,text,text,text,text,text,numeric,uuid) to authenticated;


-- ═════════════════════════════════════════════════════════════════════════════
-- 3. ORGANIZATION REGISTRATION
-- ═════════════════════════════════════════════════════════════════════════════

alter table public.ws_tblorganization
  add column if not exists clientuuid uuid;

comment on column public.ws_tblorganization.clientuuid is
  'Client-generated idempotency key for one registration attempt. A retry '
  'after a lost response returns the organization already provisioned rather '
  'than creating a second empty tenant.';

-- SCOPED TO THE OWNER, not global. A key is unguessable in practice, but
-- scoping it means one user''s key can never collide with another''s and block
-- a legitimate registration.
create unique index if not exists ux_organization_clientuuid
  on public.ws_tblorganization(owneruserid, clientuuid)
  where clientuuid is not null;


-- ─── The old signatures must GO, not sit alongside the new ones ──────────────
--
-- Adding a defaulted parameter creates an OVERLOAD. A six-argument call would
-- then match both the old six-arg function exactly and the new seven-arg one
-- by default, and Postgres refuses with "function is not unique". Migration
-- 010 hit exactly this with ws_record_delivery. Dropping first means one
-- function exists and every existing caller — seed.sql, fix_user_without_org
-- .sql, the app — keeps resolving to it.

drop function if exists ws.provision_organization(uuid,text,text,text,text,text);
drop function if exists public.ws_create_organization(text,text,text,text,text);


create or replace function ws.provision_organization(
  p_uid        uuid,
  p_orgname    text,
  p_ownername  text default '',
  p_phone      text default '',
  p_address    text default '',
  p_currency   text default 'PKR',
  p_clientuuid uuid default null
)
returns bigint
language plpgsql
security definer
set search_path = ws, public, pg_catalog
as $$
declare
  v_orgid  bigint;
  v_roleid bigint;
  v_msid   bigint;
begin
  if p_uid is null then
    raise exception 'provision_organization: no owner uid supplied'
      using errcode = '42501';
  end if;

  -- ── IDEMPOTENCY CHECK ──────────────────────────────────────────────────
  -- THE WHOLE REGISTRATION IS ONE OPERATION. Everything below — org, roles,
  -- membership, internal user, subscription, chart of accounts — happens in a
  -- single transaction, so this one check protects all of it. A retry returns
  -- the organization that already exists and provisions nothing twice.
  if p_clientuuid is not null then
    select orgid into v_orgid
    from public.ws_tblorganization
    where owneruserid = p_uid and clientuuid = p_clientuuid;

    if v_orgid is not null then
      return v_orgid;
    end if;
  end if;

  insert into public.ws_tblorganization
    (orgname, businessname, owneruserid, ownername, phone, address, currency,
     clientuuid)
  values
    (p_orgname, p_orgname, p_uid, p_ownername, p_phone, p_address, p_currency,
     p_clientuuid)
  returning orgid into v_orgid;

  perform ws.ensure_org_roles(v_orgid);

  select roleid into v_roleid
  from public.ws_tblroles
  where orgid = v_orgid and rolecode = 'owner';

  insert into public.ws_tblmemberships (orgid, authuserid, roleid)
  values (v_orgid, p_uid, v_roleid)
  returning membershipid into v_msid;

  insert into public.ws_tblinternalusers
    (orgid, authuserid, fullname, role, phone, membershipid)
  values
    (v_orgid, p_uid, coalesce(nullif(p_ownername, ''), 'Owner'), 'owner',
     nullif(p_phone, ''), v_msid);

  insert into public.ws_tblsubscriptions
    (orgid, plancode, status, trialstartdate, trialenddate, periodstart, periodend)
  values
    (v_orgid, 'free', 'trialing', current_date, current_date + 30,
     current_date, current_date + 30);

  -- Seeded HERE, inside the same transaction, since migration 011. The client
  -- no longer calls ws_seed_chart_of_accounts as a second round trip — that
  -- second call was the window where a dropped connection left the caller
  -- believing registration had failed while the tenant existed.
  perform ws.seed_chart_of_accounts(v_orgid);

  return v_orgid;
end
$$;

revoke all on function ws.provision_organization(uuid,text,text,text,text,text,uuid) from public;


create or replace function public.ws_create_organization(
  p_orgname    text,
  p_ownername  text default '',
  p_phone      text default '',
  p_address    text default '',
  p_currency   text default 'PKR',
  p_clientuuid uuid default null
)
returns bigint
language plpgsql
security definer
set search_path = ws, public, pg_catalog
as $$
declare v_uid uuid := ws.current_uid();
begin
  if v_uid is null then
    raise exception 'ws_create_organization: not authenticated'
      using errcode = '42501';
  end if;
  return ws.provision_organization(
    v_uid, p_orgname, p_ownername, p_phone, p_address, p_currency,
    p_clientuuid);
end
$$;

revoke all on function public.ws_create_organization(text,text,text,text,text,uuid) from public;
grant execute on function public.ws_create_organization(text,text,text,text,text,uuid) to authenticated;


-- ═════════════════════════════════════════════════════════════════════════════
-- 4. ONE LOOKUP FOR EVERY KEY
-- ═════════════════════════════════════════════════════════════════════════════
-- Still a READ, so it stays safe to call against an operation whose outcome is
-- unknown. Seven document types now resolve from one key.
--
-- Organizations are matched on ownership rather than ws.is_member(), because
-- the question being asked is "did MY registration land?" and the answer must
-- be available even if membership somehow did not complete.

create or replace function public.ws_lookup_clientuuid(p_clientuuid uuid)
returns table (doctype text, docid bigint, docnumber text, docdate date)
language sql
stable
security definer
set search_path = ws, public, pg_catalog
as $$
  select 'delivery'::text, d.deliveryid, d.referenceno, d.deliverydate
  from public.ws_tbldeliveries d
  where d.clientuuid = p_clientuuid and ws.is_member(d.orgid)
  union all
  select 'payment'::text, p.paymentid, p.receiptno, p.paymentdate
  from public.ws_tblpayments p
  where p.clientuuid = p_clientuuid and ws.is_member(p.orgid)
  union all
  select 'purchase'::text, pu.purchaseid, pu.referenceno, pu.purchasedate
  from public.ws_tblpurchases pu
  where pu.clientuuid = p_clientuuid and ws.is_member(pu.orgid)
  union all
  select 'vendorpayment'::text, vp.vendorpaymentid, vp.voucherno, vp.paiddate
  from public.ws_tblvendorpayments vp
  where vp.clientuuid = p_clientuuid and ws.is_member(vp.orgid)
  union all
  select 'customer'::text, c.customerid, c.customercode, c.createddate::date
  from public.ws_tblcustomers c
  where c.clientuuid = p_clientuuid and ws.is_member(c.orgid)
  union all
  select 'vendor'::text, v.vendorid, v.vendorcode, v.createddate::date
  from public.ws_tblvendors v
  where v.clientuuid = p_clientuuid and ws.is_member(v.orgid)
  union all
  select 'organization'::text, o.orgid, o.orgname, o.createddate::date
  from public.ws_tblorganization o
  where o.clientuuid = p_clientuuid and o.owneruserid = ws.current_uid();
$$;

revoke all on function public.ws_lookup_clientuuid(uuid) from public;
grant execute on function public.ws_lookup_clientuuid(uuid) to authenticated;


-- =============================================================================
-- VERIFICATION
--
--   -- same key twice = one customer, original id both times
--   select public.ws_record_customer(1, 'Test', p_clientuuid =>
--          'aaaaaaaa-0000-0000-0000-000000000001');
--   select public.ws_record_customer(1, 'TAMPERED', p_clientuuid =>
--          'aaaaaaaa-0000-0000-0000-000000000001');
--   select count(*) from public.ws_tblcustomers
--    where clientuuid = 'aaaaaaaa-0000-0000-0000-000000000001';   -- must be 1
--   select customername from public.ws_tblcustomers
--    where clientuuid = 'aaaaaaaa-0000-0000-0000-000000000001';   -- 'Test'
--
--   -- legacy caller, no key, still works and is never deduplicated
--   select public.ws_record_customer(1, 'Legacy A');
--   select public.ws_record_customer(1, 'Legacy A');              -- two rows
--
--   select count(*) from public.vw_ws_reconciliation;             -- must be 0
--   select count(*) from public.vw_ws_unbalancedentries;          -- must be 0
-- =============================================================================
